Tabbing and added cards to tabs
bootstrap-vue-next/bootstrap-vue-next pull request #1125
Opened 2023-05-26 03:01 UTC by StirStudios

Very small updates and formatting:

- Read me updates, mainly adding <b-cards> to the tabs for better visibility.

2023-05-26 03:24 UTC, VividLemon reviewed
Other than that, I don't have anything else. But even those two things aren't dealbreakers. I could see arguments for doing it either way.

2023-05-26 03:24 UTC, VividLemon commented on apps/docs/src/getting-started.md
>  ::: danger NOT PRODUCTION READY
Previously the `:::` syntax did this automatically. However, the `:::` syntax was automatically generated by the _theme_. I had reached out to Vitepress in hopes to seeing how and if we could essentially make `:::` _compile to_ a custom component, but have received no response.

2023-05-26 03:24 UTC, VividLemon commented on apps/docs/src/reference/directives/BTooltip.md
> +- click
If we're going to pick `-` over `*`, it should really be done _globally_... Just to stay consistent.

2023-05-26 03:25 UTC, VividLemon commented on apps/docs/src/getting-started.md
>  ::: danger NOT PRODUCTION READY
("Doing it automatically" was the _themes_ custom implementation of this, not necessarily a bootstrap implementation. Alert is the closest component that matched what `:::` did)

2023-05-26 15:44 UTC, StirStudios commented
Thanks for the feedback. I have gone ahead and removed the BS alert. However the * vs - seems more like a linting prepare issue. This happens on commit staging. I will see if i can revert to avoid.

2023-05-26 15:49 UTC, StirStudios commented on apps/docs/src/reference/directives/BTooltip.md
> +- click
However the * vs - seems more like a linting prepare issue. This happens on commit staging. I will see if i can revert to avoid.

2023-05-26 16:05 UTC, StirStudios commented on apps/docs/src/reference/directives/BTooltip.md
> +- click
Reviewing the code it seems in most cases - it used over * so I went ahead and converted the remaining * versions.

2023-05-26 22:43 UTC, VividLemon commented on apps/docs/src/reference/directives/BTooltip.md
> +- click
Interesting, if it happens again, perhaps we will use the other syntax than.

2023-05-26 22:47 UTC, VividLemon commented on apps/docs/src/getting-started.md
>  ::: danger NOT PRODUCTION READY
I've recently gotten a response from a Vitepress core team member about a few of these issues. This particular issue can be fixed by modifying the behavior of markdown-it. However, this particular fix isn't quite extendable to other syntaxes (say `> desc`) type syntax (afaik). So, it's my super executive decision, that moving forward, the usage should be as you have done previously, with using true html tags to provide this functionality. 

If you don't mind, could this PR address fixes for `> desc` syntax and `:::` syntax? 

* When I say `> desc` syntax, I am referring to those top level descriptions that are present throughout things like the component references

2023-05-27 00:40 UTC, StirStudios commented on apps/docs/src/getting-started.md
>  ::: danger NOT PRODUCTION READY
Okay to be clear that is what is needed:

Update `:::`
```
::: tip
The animation effect of this component is dependent on the prefers-reduced-motion media query. See the [reduced motion section of our accessibility documentation](https://getbootstrap.com/docs/5.0/getting-started/accessibility/#reduced-motion).
:::
```

to
```
<b-alert variant="info" :model-value="true">
::: tip
The animation effect of this component is dependent on the prefers-reduced-motion media query. See the [reduced motion section of our accessibility documentation](https://getbootstrap.com/docs/5.0/getting-started/accessibility/#reduced-motion).
:::
<b-alert>
```

---

Top level descriptions:
```
# Accordion

Build vertically collapsing accordions in combination with `<b-collapse>` component.
```

to

```
<p class="lead">
# Accordion

Build vertically collapsing accordions in combination with `<b-collapse>` component.
</p>
```

Or possibly a blockquote?

2023-05-27 00:48 UTC, VividLemon commented on apps/docs/src/getting-started.md
>  ::: danger NOT PRODUCTION READY
Only change is 
```
<b-alert variant="info" :model-value="true">
::: tip
The animation effect of this component is dependent on the prefers-reduced-motion media query. See the [reduced motion section of our accessibility documentation](https://getbootstrap.com/docs/5.0/getting-started/accessibility/#reduced-motion).
:::
<b-alert>
```
to 
```
<b-alert variant="info" :model-value="true">
The animation effect of this component is dependent on the prefers-reduced-motion media query. See the [reduced motion section of our accessibility documentation](https://getbootstrap.com/docs/5.0/getting-started/accessibility/#reduced-motion).
<b-alert>
```

2023-05-27 00:49 UTC, StirStudios commented on apps/docs/src/getting-started.md
>  ::: danger NOT PRODUCTION READY
Awesome on it now then!

2023-05-27 01:25 UTC, StirStudios commented on apps/docs/src/getting-started.md
>  ::: danger NOT PRODUCTION READY
I have gone ahead and made a few more adjustments for design and UI, makes things easier to read: https://github.com/bootstrap-vue-next/bootstrap-vue-next/pull/1125/commits/28297b50b7d4d94db45682975c2e327380cf5c1e

If this works I can move through and update the rest.

2023-05-27 01:44 UTC, VividLemon requested changes

2023-05-27 01:44 UTC, VividLemon commented on apps/docs/src/reference/components/form-group.md
> +  <div>
In addition to removals of <b-cards> around code blocks, it would also be helpful to remove excess div tags as well. 

Also, occasionally I have made some code like
```html
<b-button>do one thing</b-button>
<b-button>do something else</b-button>
```
When it could be wrapped in a button group
```html
<b-button-group>
<b-button>do one thing</b-button>
<b-button>do something else</b-button>
</b-button-group>
```
I'm not sure where some of these instances are, but if you ever find one, it would look nicer if they were grouped up... I think I did one on the useBreadcrumb page that I changed today.

2023-05-27 01:44 UTC, VividLemon commented on apps/docs/src/reference/directives/BTooltip.md
> +```vue-html
Nice catch

2023-05-27 01:44 UTC, VividLemon commented on apps/docs/src/reference/icons.md
> +  <b-card class="border-top-0 rounded-top-0">
If you have any other suggestions on making the docs look "nicer", I am all for seeing them. It could be a large or small change, I'm open to anything.

2023-05-27 01:44 UTC, VividLemon commented on packages/bootstrap-vue-next/CHANGELOG.md
> +- **BDropdown:** using manual control to display/hide the popover it should allow the event update:modelValue when manualBoolean is true ([ba490c9](https://github.com/bootstrap-vue-next/bootstrap-vue
You're changelog is out of sync. During the fixing of the merge conflict, just copy the existing one on the repo, then paste it into yours. 

Basically, the * to - fixes are fine, but you can leave the changelog alone

2023-05-27 01:44 UTC, VividLemon commented on packages/nuxt/CHANGELOG.md
> +- **nuxt:** remove nuxt.ts from main package & @nuxt/kit from dependencies -- use package @bootstrap-vue-next/nuxt (readme coming soon)
Same as above, overall, just leave the changelog alone. I figure it was a global find/replace and just an oversight.

2023-05-27 01:44 UTC, VividLemon commented on apps/docs/src/reference/components/form-group.md
> +  <div>
I could also just do this one tomorrow.

2023-05-27 21:48 UTC, StirStudios commented on apps/docs/src/reference/icons.md
> +  <b-card class="border-top-0 rounded-top-0">
I think I have done as much as possible to this point. I would love to get your feedback on the TOC offcanvas idea I put together. Let's see if we can get a merge happening here.

2023-05-27 21:54 UTC, VividLemon commented on apps/docs/src/reference/icons.md
> +  <b-card class="border-top-0 rounded-top-0">
There's still a merge conflict

2023-05-27 22:12 UTC, StirStudios commented on apps/docs/src/reference/icons.md
> +  <b-card class="border-top-0 rounded-top-0">
Ah, did a quick copy and paste and seems to be passing now. Will add the tiny theming tweaks for the useBreadcrumb.md later. Fingers crossed this time!

2023-05-27 22:22 UTC, StirStudios commented
@VividLemon seems there is a build failure not sure that is something I can fix?

2023-05-27 22:33 UTC, VividLemon commented
> @VividLemon seems there is a build failure not sure that is something I can fix?

A component in BTooltip.md is missing an end tag

2023-05-27 22:49 UTC, StirStudios commented
Always something!

2023-05-27 23:12 UTC, merged

2023-05-27 23:51 UTC, VividLemon commented
> Always something! It's fixed but is still failing it seems!

![image](https://github.com/bootstrap-vue-next/bootstrap-vue-next/assets/31498096/2db50cd1-2985-4625-bd71-2ce89d9dace4)