feat: use options in to install plugin to allow select some component…
bootstrap-vue-next/bootstrap-vue-next pull request #1170
Opened 2023-06-07 09:00 UTC by sfe-efficy

# Describe the PR

Use options in to install plugin to allow select some components, directives or linked BToastPlugin configuration

## Small replication

If the change is large enough, a small replication can help demonstrate the changes made. This is optional, but can help observe the intended changes. A mentioned issue that contains a replication also works.

## PR checklist

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix :bug: - `fix(...)`
- [x] Feature - `feat(...)`
- [ ] ARIA accessibility - `fix(...)`
- [ ] Documentation update - `docs(...)`
- [ ] Other (please describe)

**The PR fulfills these requirements:**

- [x] Pull request title and all commits follow the [**Conventional Commits**](https://www.conventionalcommits.org/) convention or has an [**override**](https://github.com/googleapis/release-please#how-can-i-fix-release-notes) in this pull request body **This is very important, as the `CHANGELOG` is generated from these messages, and determines the next version type. Pull requests that do not follow conventional commits or do not have an override will be denied**

2023-06-09 14:20 UTC, VividLemon commented on packages/bootstrap-vue-next/src/BootstrapVue.ts
> +    const selectedComponents =
If you're trying to replicate the behavior as shown in https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/packages/nuxt/src/module.ts#L23 , this wouldn't quite be the same

The main difference being if you did {all: true, someComponent: false}, this would still mark that someComponent as being true. Whereas, in the Nuxt module, the above is valid and will give you, everything but someComponent. I don't think this does that here.

2023-06-15 00:42 UTC, VividLemon requested changes
https://github.com/bootstrap-vue-next/bootstrap-vue-next/pull/1170#discussion_r1224372135

2023-06-15 07:34 UTC, sfe-efficy commented on packages/bootstrap-vue-next/src/BootstrapVue.ts
> +    const selectedComponents =
Hi! done, I review the original code and I touch some parts that I guess could be improved.
And also I unified the logical to don't have duplicate code

2023-06-20 00:17 UTC, VividLemon requested changes

2023-06-25 00:21 UTC, VividLemon commented
In my above statement, I claimed that `You won't be able to import from other packages`. This was somewhat misleading, as at the time, I didn't notice that you were keeping it in the bootstrap-vue-next package, then importing it into the nuxt package... I'm still not 100% sure if this would work... Regardless, I still think it's okay to duplicate this util in the nuxt & bootstrap-vue-next package.

2023-06-26 19:43 UTC, sfe-efficy commented on packages/nuxt/src/module.ts
> +import {parseActiveImports} from 'bootstrap-vue-next'
Done, I was busy for a while, I got time today to duplicate the code

2023-06-26 19:43 UTC, sfe-efficy commented on packages/bootstrap-vue-next/src/utils/exports/index.ts
> +export {BvEvent, BvTriggerableEvent, BvCarouselEvent, parseActiveImports} from '..'
Done, I was busy for a while, I got time today to duplicate the code

2023-06-26 19:44 UTC, sfe-efficy commented
> In my above statement, I claimed that `You won't be able to import from other packages`. This was somewhat misleading, as at the time, I didn't notice that you were keeping it in the bootstrap-vue-next package, then importing it into the nuxt package... I'm still not 100% sure if this would work... Regardless, I still think it's okay to duplicate this util in the nuxt & bootstrap-vue-next package.

It's ok, it was easy to resolve this topic

2023-07-04 14:51 UTC, merged