feat(BOffcanvas): adds teleport to property.
bootstrap-vue-next/bootstrap-vue-next pull request #1187
Opened 2023-06-14 14:53 UTC by phlegx

# Describe the PR

Like described in the official [documentation of vue](https://vuejs.org/guide/scaling-up/ssr.html#teleports), SSR deployments should consider to use an own DOM node for teleports:

_Avoid targeting body when using Teleports and SSR together - usually, `<body>` will contain other server-rendered content which makes it impossible for Teleports to determine the correct starting location for hydration. Instead, prefer a dedicated container, e.g. `<div id="teleported"></div>` which contains only teleported content._

Every bootstrap-vue component, that uses teleport, cannot be configured with `:to=` property. Default is `body` and SSR deployments need to set teleport `:to=` to e.g. `#body-teleports`.

**This PR introduces `to` property for `BOffcanvas`.**

Solves issue #1178 for `BOffcanvas`.

## Small replication

Required SSR rendering of teleport components, by using a unique DOM node outside app node (solves hydration node mismatch).

```html
<b-offcanvas to="#body-teleports">
  ...
</b-offcanvas>
```

with `index.html` like:

```html
...
<body>
  <div id="body-teleports"></div>
  <div id="app"></div>
</body>
```

## PR checklist

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix :bug: - `fix(...)`
- [x] Feature - `feat(...)`
- [ ] ARIA accessibility - `fix(...)`
- [ ] Documentation update - `docs(...)`
- [ ] Other (please describe)

**The PR fulfills these requirements:**

- [x] Pull request title and all commits follow the [**Conventional Commits**](https://www.conventionalcommits.org/) convention or has an [**override**](https://github.com/googleapis/release-please#how-can-i-fix-release-notes) in this pull request body **This is very important, as the `CHANGELOG` is generated from these messages, and determines the next version type. Pull requests that do not follow conventional commits or do not have an override will be denied**

2023-06-15 00:14 UTC, VividLemon requested changes

2023-06-15 00:14 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BOffcanvas/BOffcanvas.vue
>    static?: Booleanish
rename prop static to `teleportDisabled`

Declare it a breaking change

2023-06-15 00:14 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BOffcanvas/BOffcanvas.vue
> +  to?: string | RendererElement | null | undefined
Rename prop `to` to prop `teleportTo`

2023-06-15 00:41 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BOffcanvas/BOffcanvas.vue
> +  to?: string | RendererElement | null | undefined
I'm not sure where you're getting these prop definitions from. The Api documentation is located here
https://vuejs.org/api/built-in-components.html#teleport
You may prefer `to?: string | HTMLElement`

2023-06-15 08:02 UTC, phlegx commented on packages/bootstrap-vue-next/src/components/BOffcanvas/BOffcanvas.vue
> +  to?: string | RendererElement | null | undefined
I got the definition from here: https://github.com/vuejs/core/blob/60cd23c7520f9098bf31fc2d0c09d58ded75f173/packages/runtime-core/src/components/Teleport.ts#L19

2023-06-15 11:00 UTC, phlegx commented on packages/bootstrap-vue-next/src/components/BOffcanvas/BOffcanvas.vue
>    static?: Booleanish
@VividLemon done!

2023-06-15 14:28 UTC, VividLemon requested changes

2023-06-15 14:28 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BOffcanvas/BOffcanvas.vue
> +  <teleport :to="props.teleportTo" :disabled="teleportDisabledBoolean">
```suggestion
  <teleport :to="teleportTo" :disabled="teleportDisabledBoolean">
```

2023-06-15 16:49 UTC, phlegx commented
@VividLemon I don't understand how to solve this merge conflict. My code looks ok.

2023-06-16 19:13 UTC, VividLemon commented
> @VividLemon I don't understand how to solve this merge conflict. My code looks ok.

You're the one that caused the conflict https://github.com/bootstrap-vue-next/bootstrap-vue-next/pull/1189 . All you need to do is merge main into your branch

2023-06-16 20:29 UTC, VividLemon requested changes
https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/2737f30b548cf055277f5436c3cf76d6dd18cfd9/apps/docs/.vitepress/theme/Layout.vue#L82 will need a change

2023-06-19 11:44 UTC, closed without merging