feat(BToast): Simplify toast plugin
bootstrap-vue-next/bootstrap-vue-next pull request #1210
Opened 2023-06-23 02:15 UTC by aceofwings

# Describe the PR

Simplify toast plugin.  The plugin had a lot of misc code that were ideas and features that could possibly be developed further. None the less it was clutter and to start from the beginning makes more sense. 

Add documentation and client-side guard. I do not know if it is necessary though I remember the hassle of deploying docs in the olden days to due compilation errors with  vuepress. 

## PR checklist

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix :bug: - `fix(...)`
- [x] Feature - `feat(...)`
- [ ] ARIA accessibility - `fix(...)`
- [x] Documentation update - `docs(...)`
- [ ] Other (please describe)

**The PR fulfills these requirements:**

- [x] Pull request title and all commits follow the [**Conventional Commits**](https://www.conventionalcommits.org/) convention or has an [**override**](https://github.com/googleapis/release-please#how-can-i-fix-release-notes) in this pull request body **This is very important, as the `CHANGELOG` is generated from these messages, and determines the next version type. Pull requests that do not follow conventional commits or do not have an override will be denied**

2023-06-23 16:59 UTC, VividLemon commented
> Add documentation and client-side guard. I do not know if it is necessary though I remember the hassle of deploying docs in the olden days to due compilation errors with vuepress.

It is not necessary

The simplification of the plugin is a welcome change. However, I would think about not writing tests for it. I'd like to develop this experience further. I would like to decouple toasts from b-container. It would be nice if the `useToast` function would dynamically mount/unmount the toaster container, but I'm not sure how I could achieve this.

Hypothetically, if you could render a VNode in a composable, this would fix our issues:

```ts
export default () => {
  const toasts = []
  const show = () => {
    toasts.push(h(BToast))
  }
toasts.forEach((el) => document.body.appendChild(el))
}
```
However, I don't know if this is possible.

An alternative solution could be to use provide/inject. Where
```ts
export default () => {
  const parent = inject(BToasterPluginKey)
  const show = () => {
    parent.addToast()
  }
  return {show}
}
```
Then have some component render that. Similar to BContainer rendering it, but not BContainer... A plugin would be preferred as opposed to a real component.

Vuetify solves this by using real components -- VApp. But I'd like to avoid a component requirement for this. If possible, I'd prefer a plugin option that you can call once. You can mount elements in plugins. For example, the BTooltip directive does this. So if we combined rendering BToaster through a plugin, then had BToaster using a provide/inject system, we could accomplish a more streamlined system. 

Though, in this situation, BToast component would need some modifications as if someone did https://bootstrap-vue.org/docs/components/toast and created a toast component, it wouldn't really be usable. I don't know how one would make this usable... But perhaps the simplicity of just calling a method would mean that the exact usage from bootstrap-vue would justify it being deprecated. 

Bootstrap-vue had it "easy", as they relied on portal-vue, as opposed to Vue 3's teleport. In portal-vue, you can check for a targets existence. In their situation, they can check for the existence of BToaster, if it doesn't exist, they can make it exist. If it does exist, they can just teleport to it. This is not something you can do in Vue 3. First off, Vue 3's teleport lacks the ability to wait for a component to exist. The second issue, is you can't functionally determine if the target exists. So, we need to get creative, and likely will need deprecation & removals.

2023-06-23 17:01 UTC, VividLemon commented
>  It would be nice if the useToast function would dynamically mount/unmount the toaster container, but I'm not sure how I could achieve this.

"Maybe" we could do something like
```ts
const toaster = createSharedComposable(() => {
  const toaster = createApp(BToaster) // append to body
})

const useToast = () => {
  toaster()
  // Create and append children toasts
}
```
But I don't know if this would work.

2023-06-24 23:29 UTC, aceofwings commented
> > It would be nice if the useToast function would dynamically mount/unmount the toaster container, but I'm not sure how I could achieve this.
> 
> "Maybe" we could do something like
> 
> ```ts
> const toaster = createSharedComposable(() => {
>   const toaster = createApp(BToaster) // append to body
> })
> 
> const useToast = () => {
>   toaster()
>   // Create and append children toasts
> }
> ```
> 
> But I don't know if this would work.

I see where you are going with this and I have reviewed the tool tip code. The toast code can be readily written to mount another app to a appended container. We can readily pass down the simplified code (ToastController) to be shared between the instances (I think).  Just to confirm it is a totally acceptable practice due to library limitation to spawn multiple app instances instead of using  real components?

2023-06-25 00:17 UTC, VividLemon commented
>  Just to confirm it is a totally acceptable practice due to library limitation to spawn multiple app instances instead of using real components? 

idfk. But I say "just do it".

2023-06-25 00:40 UTC, VividLemon commented
Would you prefer me to merge this now, or are you planning on trying to implement what has been discussed and would prefer me to wait?

2023-06-25 15:28 UTC, VividLemon commented
I apologize, but there was an issue with the scss code for BToast. In Bootstrap v5.3, they changed some things that affected the 'alpha' function for BToast. As a temporary measure, I have removed the scss from BToast, as ultimately the component didn't really work to begin with. I somewhat forgot about this PR that changed some of how it functioned, but even if I did not forget about it, I would likely have still made the temporary change.

If you would like, it would be a large help to rebuild the scss (perhaps some of it is unneeded and can be removed... Perhaps it all could have been removed and there is no issue) But some additional information can be found here https://github.com/twbs/bootstrap/issues/38687 as it is not a bug to Bootstrap and will require some fixing on our end

2023-06-25 19:27 UTC, aceofwings commented
No worries , I already did a very small adjustment to get things to compile properly. I will overhaul it. The scss was orignally written as bootstrap v4 did not support toasts. Since the release of 5.3 they have released subtle color pallets. This will give us the same lightly color background. let me see what i can do

2023-06-26 01:14 UTC, aceofwings commented
So accidently left out the minor changes (the small adjustment I mentioned earlier) removing the compilation error you were talking about above.

2023-07-04 14:51 UTC, VividLemon commented
https://github.com/bootstrap-vue-next/bootstrap-vue-next/pull/1210#issuecomment-1605800203

2023-07-10 01:48 UTC, aceofwings commented
I looked into using bg-opacity and bg-${variant} classes and styling assignments. Sadly, the default coloring looks a little to harsh and is not as elegant as I hoped. None the less the css I pushed 2 weeks ago covers the compilation error you referenced above. I think the best thing to do is keep bootstrap vue's original toast color pallet and in the near future address opacity and solid settings in the toast component.

2023-07-10 01:50 UTC, VividLemon commented
> I looked into using bg-opacity and bg-${variant} classes and styling assignments. Sadly, the default coloring looks a little to harsh and is not as elegant as I hoped. None the less the css I pushed 2 weeks ago covers the compilation error you referenced above. I think the best thing to do is keep bootstrap vue's original toast color pallet and in the near future address opacity and solid settings in the toast component.

Why is any of the custom css required? What parts of the component are not already handled by Bootstrap?

2023-07-10 02:10 UTC, aceofwings commented
Handling toast varieties is done by bg-color and bg-opacities. However, the contrast for doing them is poor. I suggest we maintain color pallet as implemented in the bootstrap vue and later when I implement the solid prop, remove opacity styling and have it computed in the component. Attached are pictures of bootstraps' color pallet vs bootstrap vues. 
 
<img width="277" alt="toast 1" src="https://github.com/bootstrap-vue-next/bootstrap-vue-next/assets/5874741/d0f5700b-862d-438c-9199-f98d325e1863">
<img width="271" alt="toast 2" src="https://github.com/bootstrap-vue-next/bootstrap-vue-next/assets/5874741/13fd9fc2-82ae-4f42-80c2-830e06bfabf9">
<img width="272" alt="toast 3" src="https://github.com/bootstrap-vue-next/bootstrap-vue-next/assets/5874741/391dde5a-9b7f-4708-a2cb-10056d39823f">

2023-07-10 02:17 UTC, VividLemon commented
> Handling toast varieties is done by bg-color and bg-opacities. However, the contrast for doing them is poor. I suggest we maintain color pallet as implemented in the bootstrap vue and later when I implement the solid prop, remove opacity styling and have it computed in the component. Attached are pictures of bootstraps' color pallet vs bootstrap vues.
> <img alt="toast 1" width="277" src="https://user-images.githubusercontent.com/5874741/252194348-d0f5700b-862d-438c-9199-f98d325e1863.PNG"> <img alt="toast 2" width="271" src="https://user-images.githubusercontent.com/5874741/252194365-13fd9fc2-82ae-4f42-80c2-830e06bfabf9.png"> <img alt="toast 3" width="272" src="https://user-images.githubusercontent.com/5874741/252194373-391dde5a-9b7f-4708-a2cb-10056d39823f.png">

You will also need to keep in mind that Bootstrap v5.3 implements color modes. So the existing code will need to change to compensate for this -- I don't mind about custom css to make up for some shortcomings of bootstrap, but color modes complicates things.

2023-07-10 09:18 UTC, sceee commented
Shouldn't this just reflect the default styling of bootstrap?
If someones wants to customize it, it is probably best just use the [color schemes starting with Bootstrap 5.3](https://getbootstrap.com/docs/5.3/components/toasts/#color-schemes).
This uses `text-*` and `text-bg-*` classes [for styling](https://getbootstrap.com/docs/5.3/helpers/color-background/).

So if it would be possible to set these classes as prop (or via a `variant` prop for both (text and bg) which then translates into those classes), it would reflect the default bootstrap 5.3+ behavior.

Someone could probably still use [CSS Variables to override](https://getbootstrap.com/docs/5.3/components/toasts/#variables) some general styling.

2023-07-11 00:18 UTC, VividLemon requested changes

2023-07-11 00:18 UTC, VividLemon commented on apps/docs/.vitepress/theme/index.ts
> +    if (!import.meta.env.SSR) {
Remove this. -- The SSR portion

2023-07-11 00:18 UTC, VividLemon commented on apps/docs/src/docs/components/toast.md
> +The toast plugin allows for global access and handling of toasts for a single `<b-container>` instance.
`<BContainer>` > `<b-container>` use PascalCase

2023-07-11 00:18 UTC, VividLemon commented on apps/docs/src/docs/components/toast.md
> +```js
```suggestion
```ts
```
(Though it technically makes no difference

2023-07-11 00:18 UTC, VividLemon commented on apps/docs/src/docs/components/toast.md
> +Then designate a `<b-container>` component using the toast prop.
Review above comment

2023-07-11 00:18 UTC, VividLemon commented on apps/docs/src/docs/components/toast.md
> +<b-container :toast="true" fluid="sm" position="position-fixed"></b-container>
Review above comment

Also, use <BContainer /> syntax over <BContainer></BContainer>

2023-07-11 00:18 UTC, VividLemon commented on apps/docs/src/docs/components/toast.md
> +```js
```suggestion
```ts
```

2023-07-11 00:18 UTC, VividLemon commented on apps/docs/src/docs/components/toast.md
> +//setup function
```suggestion
```
This is a given

2023-07-11 00:18 UTC, VividLemon commented on apps/docs/src/docs/components/toast.md
> +let toast = useToast()
```suggestion

const toast = useToast()
```

2023-07-11 00:18 UTC, VividLemon commented on apps/docs/src/docs/components/toast.md
> +<b-button class="" @click="show1">Show Toast</b-button>
Pascal case. Also, fix your indentation

2023-07-11 00:18 UTC, VividLemon commented on apps/docs/src/docs/components/toast.md
> +```vue
Review other similar documentation examples. There is a difference between vue-html and vue. One is for pure template stuff, the other is for both template and scripts.

Put a line break between the two.

Code blocks indentations restart (if that makes sense)

2023-07-11 00:18 UTC, VividLemon commented on apps/docs/src/docs/components/toast.md
> +let show1 = () => {
Use const

2023-07-11 00:18 UTC, VividLemon commented on apps/docs/src/docs/components/toast.md
> +let show2 = () => {
Use const

2023-07-11 00:18 UTC, VividLemon commented on apps/docs/src/docs/components/toast.md
> +<b-button class="" variant="danger" @click="variantshow1">Show Danger</b-button>
Pascal case

2023-07-11 00:18 UTC, VividLemon commented on apps/docs/src/docs/components/toast.md
> +<b-button class="" variant="danger" @click="variantshow1">Show Danger</b-button>
Wrap in` <template>`

2023-07-11 00:18 UTC, VividLemon commented on apps/docs/src/docs/components/toast.md
> +<b-button class="ms-2" variant="success" @click="variantshow4">Show Sucess</b-button>
```suggestion
<b-button class="ms-2" variant="success" @click="variantshow4">Show Sucess</b-button>

```

2023-07-11 00:18 UTC, VividLemon commented on apps/docs/src/docs/components/toast.md
> +let toast = useToast()
const
(this goes for everything below)

2023-07-11 00:18 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BToast/plugin.ts
> +export function useToast(): ToastInstance | undefined {
Use arrow function syntax over functions (assuming the function does not access `this`)

2023-07-20 02:10 UTC, aceofwings commented on apps/docs/.vitepress/theme/index.ts
> +    if (!import.meta.env.SSR) {
so if I remove this then the docs do not work with the toast implementation.

2023-07-20 02:11 UTC, aceofwings commented on apps/docs/.vitepress/theme/index.ts
> +    if (!import.meta.env.SSR) {
nvm

2023-07-20 03:24 UTC, aceofwings commented
I do recommend for future we revisit the suggestions above. Perhaps come to terms with have 2 implementations. One driven by B-Container as seen in the Veutify eco system. We are trying to create a bootstrap eco system so I would not shy away from real component solution. As well as maintain a separate app for spawning toasts. As mentioned in another issue multiple apps pollute the debugging tool Vue has to offer.

2023-07-27 23:32 UTC, closed without merging

2023-07-27 23:33 UTC, VividLemon commented
@aceofwings Why did you close this?