feat: adapt close button of BOffcanvas, BModal and BAlert for better customization.
bootstrap-vue-next/bootstrap-vue-next pull request #1254
Opened 2023-07-06 18:55 UTC by phlegx

# Describe the PR

Unify `BCloseButton` on  close button of `BOffcanvas`, `BModal` and `BAlert` and better custom button handling.

## Small replication

Component `BOffcanvas`:

```vue
<template>
  ...
  <b-link v-b-toggle:my-offcanvas>Open Offcanvas</b-link>
  <b-offcanvas id="my-offcanvas" header-close-class="foobar">
    <template #header-close>
      <span><i>Close</i></span>
    </template>
    My offcanvas content.
  </b-offcanvas>

  <b-link v-b-toggle:my-offcanvas-two>Open Offcanvas</b-link>
  <b-offcanvas id="my-offcanvas-two" header-close-class="foobar">
    My offcanvas content.
  </b-offcanvas>
  ...
</template>
```
Component `BModal`:

```vue
<template>
  ...
  <b-link v-b-toggle:my-modal>Open Modal</b-link>
  <b-modal id="my-modal" header-close-class="foobar" header-close-variant="warning">
    <template #header-close>
      <strong>Close</strong>
    </template>
    My modal content.
  </b-modal>

  <b-link v-b-toggle:my-modal-dark>Open Modal</b-link>
  <b-modal
    id="my-modal-dark"
    header-bg-variant="dark"
    header-close-class="foobar"
    header-close-white
  >
    My modal content.
  </b-modal>
  ...
</template>
```
Component `BAlert`:

```vue
<template>
  ...
  <b-alert
    v-model="dismissibleAlert"
    close-class="foobar"
    close-variant="warning"
    dismissible
  >
    <template #close>Close</template>
    My alert content.
  </b-alert>
  
  <b-alert
    v-model="dismissibleAlert"
    variant="dark"
    close-class="foobar"
    close-variant="warning"
    close-white
    dismissible
  >
    My alert content.
  </b-alert>
  ...
</template>

<script setup lang="ts">
import {ref} from 'vue'
const dismissibleAlert = ref(true)
</script>
```

Custom close buttons get style class `btn-close-custom` instead of `btn-close` and can be freely customized. Adding property `header-close-class` (for `BOffcanvas` and `BModal`) and `close-class` (for `BAlert`) with e.g. Bootstrap button classes can help to style the custom close button. Adding property `header-close-white` (for `BOffcanvas` and `BModal`) and `close-white` (for `BAlert`). Slot `header-close` was added to get same functionalities as in bootstrap-vue for Vue2.

Like discussed in PR #1206, `BCloseButton` remains as is and custom close buttons are added with `BButton` and with own content slot.

## PR checklist

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix :bug: - `fix(...)`
- [x] Feature - `feat(...)`
- [ ] ARIA accessibility - `fix(...)`
- [ ] Documentation update - `docs(...)`
- [ ] Other (please describe)

**The PR fulfills these requirements:**

- [x] Pull request title and all commits follow the [**Conventional Commits**](https://www.conventionalcommits.org/) convention or has an [**override**](https://github.com/googleapis/release-please#how-can-i-fix-release-notes) in this pull request body **This is very important, as the `CHANGELOG` is generated from these messages, and determines the next version type. Pull requests that do not follow conventional commits or do not have an override will be denied**

2023-07-10 12:37 UTC, phlegx commented
@VividLemon can this be merged now, please?

2023-07-10 23:57 UTC, VividLemon requested changes

2023-07-10 23:57 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BAlert/BAlert.vue
> -    closeContent: undefined,
Why have you removed this and some other props?

2023-07-10 23:57 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BAlert/BAlert.vue
> +  'close': []
According to the spec, both close and closed exist on Alert. Though, closed is fired after transitions have been completed. https://getbootstrap.com/docs/5.3/components/alerts/#events

If you add event listeners to the transition, you would be able to add in both events.

2023-07-10 23:57 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BAlert/BAlert.vue
> +        <BCloseButton v-else ref="closeButton" v-bind="closeAttrs" @click="hide" />
You added a template ref here, but didn't ever seem to use it.

2023-07-10 23:57 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BModal.vue
> +const headerCloseAttrs = computed(() => ({
I'm not a huge fan of the computed "attrs" objects. I may remove them out soon. 

In my mind, it makes it a bit difficult to view what is happening to what when you're looking at the template. The only instance where, in my mind, that attrs declarations like this should be made is when the attributes are shared between some components.

This however doesn't need to be fixed. This may be something that I do in the coming future.

2023-07-10 23:57 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BOffcanvas/BOffcanvas.vue
> +                  ref="closeButton"
It appears you didn't use this template ref

2023-07-11 14:26 UTC, phlegx commented on packages/bootstrap-vue-next/src/components/BAlert/BAlert.vue
> -    closeContent: undefined,
Re-added prop and logic for `closeContent`. `dismissLabel` changed to `closeLabel` like described in the commit msg. No other props were removed or changed. Added props `closeClass` and `closeWhite`.

2023-07-11 14:27 UTC, phlegx commented on packages/bootstrap-vue-next/src/components/BOffcanvas/BOffcanvas.vue
> +                  ref="closeButton"
Fixed!

2023-07-12 01:37 UTC, VividLemon requested changes

2023-07-12 01:37 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BAlert/BAlert.vue
> -        <BCloseButton v-else :aria-label="dismissLabel" v-bind="closeAttrs" @click="closeClicked" />
The issue with adding the aria-label into the closeAttrs, it comes with a drawback of the above BButton's and with screen readers. Normally someone is going to want the content on the inside of the button to be read, but an aria label wont read it. So, imo, adding aria-label onto the above bbutton doesn't make much sense.

2023-08-03 13:45 UTC, phlegx commented on packages/bootstrap-vue-next/src/components/BAlert/BAlert.vue
> -        <BCloseButton v-else :aria-label="dismissLabel" v-bind="closeAttrs" @click="closeClicked" />
Solved!

2023-08-06 18:08 UTC, VividLemon commented
Once the conflict is fixed I can get this out

2023-08-07 09:21 UTC, phlegx commented
PR is ready!

2023-08-08 19:22 UTC, phlegx commented
When can this PR be merged?

2023-08-15 03:12 UTC, merged