BTable items nested object
bootstrap-vue-next/bootstrap-vue-next pull request #1308
Opened 2023-07-19 13:45 UTC by makroxyz

# This PR solves #957 

Show nested objects table rows also using a dot key. Look at issue #957 

The fix is very simple using ```radash``` library

2023-07-19 13:56 UTC, VividLemon commented
I can't accept an addition to the dependencies. I apologize

2023-07-19 19:32 UTC, makroxyz commented
Ok, tomorrow I will try w/o adding any dependency

2023-07-19 20:36 UTC, VividLemon commented
> Ok, tomorrow I will try w/o adding any dependency

Its an implicit rule. I debated for awhile if adding vueuse was worth it. However, in that case, the decision was great as we use vueuse extensively. You can either copy the code from their library, reinvent the wheel, or pick one up on SO. There doesn't seem to be some great out of the box way in JS to achieve that feature.

> Anyway can I add a busyText or loadingText prop to BTable in order to translate the "loading" message in table-busy slot without override the entire slot?

Certainly. I'm not sure the best name for the prop, perhaps "busyLoadingText"? It could be beneficial to add the prop and also a slot to make it more vercetile. Any hard coded text should be in a prop or slot for obvious i18n reasons.

2023-07-19 22:31 UTC, dnewkerk commented
@makroxyz thanks for working on this... need this feature from the old BootstrapVue as well.

@VividLemon instead of a dependency, perhaps we could just add a `get` method to `utils/object.ts`?:
https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/packages/bootstrap-vue-next/src/utils/object.ts

This is the implementation in Radash:
https://github.com/rayepps/radash/blob/master/src/object.ts#L214
https://radash-docs.vercel.app/docs/object/get

2023-07-20 06:40 UTC, makroxyz commented
Have a look if now it's OK

2023-07-20 13:00 UTC, VividLemon requested changes

2023-07-20 13:00 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BTable/BTableLite.vue
> +import {get} from '../../utils/object'
Namespace this from utils/ not utils/object

2023-07-20 13:37 UTC, makroxyz commented
done! 
I also removed row 358  from BTableLite.vue

2023-07-20 13:53 UTC, merged