feat: set default options for components
bootstrap-vue-next/bootstrap-vue-next pull request #1387
Opened 2023-08-23 14:10 UTC by tada5hi

# Describe the PR

A clear and concise description of what the pull request does.

## Small replication

A small replication or video walkthrough can help demonstrate the changes made. This is optional, but can help observe the intended changes. A mentioned issue that contains a replication also works.

## PR checklist

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix :bug: - `fix(...)`
- [x] Feature - `feat(...)`
- [ ] ARIA accessibility - `fix(...)`
- [ ] Documentation update - `docs(...)`
- [ ] Other (please describe)

**The PR fulfills these requirements:**

- [x] Pull request title and all commits follow the [**Conventional Commits**](https://www.conventionalcommits.org/) convention or has an [**override**](https://github.com/googleapis/release-please#how-can-i-fix-release-notes) in this pull request body **This is very important, as the `CHANGELOG` is generated from these messages, and determines the next version type. Pull requests that do not follow conventional commits or do not have an override will be denied**

2023-08-24 11:15 UTC, tada5hi commented
@VividLemon would be great if you could have a look on this 🙏

2023-09-02 18:41 UTC, VividLemon requested changes

2023-09-02 18:41 UTC, VividLemon commented on packages/bootstrap-vue-next/src/utils/options.ts
> +import {hasInjectionContext, inject, provide} from 'vue'
```suggestion
import {type App, hasInjectionContext, inject, provide} from 'vue'
```

2023-09-02 18:41 UTC, VividLemon commented on packages/bootstrap-vue-next/src/utils/options.ts
> +import {hasInjectionContext, inject, provide} from 'vue'
And whatever the correct order it flags

2023-09-02 18:41 UTC, VividLemon commented on packages/bootstrap-vue-next/src/utils/options.ts
> +export function injectComponentOptions(key: `${ComponentName}`): Record<string, any> {
Use arrow functions

2023-09-02 18:41 UTC, VividLemon commented on packages/bootstrap-vue-next/src/utils/options.ts
> +export function provideComponentOptions<T extends Record<string, any>>(
Use arrow functions

2023-09-02 18:41 UTC, VividLemon commented on packages/bootstrap-vue-next/src/utils/options.ts
> +export function injectComponentOptions(key: `${ComponentName}`): Record<string, any> {
Why is TS any not throwing here

2023-09-02 18:41 UTC, VividLemon commented on packages/bootstrap-vue-next/src/utils/options.ts
> +export function provideComponentOptions<T extends Record<string, any>>(
Why is TS any not throwing here

2023-09-02 18:41 UTC, VividLemon commented on packages/bootstrap-vue-next/src/types/BootstrapVueOptions.ts
> +  BToast?: boolean | ToastOptions
Toast is an odd option to create options for since it doesn't really work

2023-09-02 18:41 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BToast/plugin.ts
> +import type {ColorVariant, ContainerPosition} from '../../types'
So you created an "set default options for components", but this isn't really a template for setting default options for components. 

The issue that I have with this is that it's likely going to be redone in the future. Eventually I'm going to overhaul how toasts are used.

2023-09-15 02:00 UTC, VividLemon commented
Also merge conflict

2023-09-23 18:24 UTC, closed without merging

2023-09-23 18:24 UTC, VividLemon commented
This is now a month old. This doesn't really solve the core issue that it doesn't really "set default options for components". Nor does it really set a default foundation to roll out to do so. It is stale, there has been no action of resurrection, and BToast has seen a complete overhaul in such time. Closing.