Fix checkbox array and radio primitives
bootstrap-vue-next/bootstrap-vue-next pull request #1388
Opened 2023-08-23 14:39 UTC by xvaara

close #1382 

The unchecked value caused a little headache, but hopefully this is ok.

2023-08-24 11:26 UTC, xvaara commented
@VividLemon do you see any problems with this one?

2023-08-28 14:25 UTC, VividLemon requested changes
This isn't to say that that these are issues, but they seem to be issues. I went through many initial designs when trying out this, and there are a few syncing issues. You not only have to deal with the traditional parent-child, but you also have to deal with coordinating with that group for those parent-child changes.

2023-08-28 14:25 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BFormCheckbox/BFormCheckbox.vue
> -watch(modelValue, (newValue) => {
What happens if the modelValue is modified externally. How does parentData get informed of that change? In the parent component, lets say there is a toggle button that changes the modelValue. If it's in a group, how is the group informed that a child has changed?

2023-08-28 14:25 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BFormRadio/BFormRadio.vue
> -watch(modelValue, (newValue) => {
Same issue as above

2023-08-28 14:26 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BFormCheckbox/BFormCheckbox.vue
> -watch(modelValue, (newValue) => {
```html
<BFormCheckboxGroup v-model="foo">
  <BFormCheckbox v-model="bar" />
</BFormCheckboxGroup>
<BButton @click="bar = !bar" />
{{foo}}
```

2023-08-29 07:10 UTC, xvaara commented on packages/bootstrap-vue-next/src/components/BFormCheckbox/BFormCheckbox.vue
> -watch(modelValue, (newValue) => {
That seems weird way to use the components didn't even think about that. 😄

2023-08-29 22:38 UTC, xvaara commented on packages/bootstrap-vue-next/src/components/BFormCheckbox/BFormCheckbox.vue
> -watch(modelValue, (newValue) => {
So when bar changes, should checkbox (if true) search foo for the old value, remove it and add new value? I'm not quite sure what this should do.

2023-08-30 01:21 UTC, xvaara commented
https://stackblitz.com/edit/vitejs-vite-pqd3b7?file=src%2FApp.vue

A demo using this build

2023-09-02 18:19 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BFormCheckbox/BFormCheckbox.vue
> +    console.log('set', newValue, props.value, props.uncheckedValue)
Deal with these linting warns. Either through suppressing them or fixing them (fix the 'oldValue' is defined but never used remove this, and you probably don't need the other console warn)

2023-09-05 11:59 UTC, xvaara commented on packages/bootstrap-vue-next/src/components/BFormCheckbox/BFormCheckbox.vue
> +    console.log('set', newValue, props.value, props.uncheckedValue)
It seems my eslint is broken in my vscode :D

2023-09-05 18:51 UTC, VividLemon approved these changes
Assuming you've tested things and they're working, you're free to merge this in.

2023-09-05 21:35 UTC, merged