fixed BOffcanvas and BModal hide event
bootstrap-vue-next/bootstrap-vue-next pull request #1527
Opened 2023-10-19 07:25 UTC by makroxyz

# Describe the PR

fixes #1526

2023-10-19 14:26 UTC, VividLemon commented
```ts
const hide = (trigger = '') => {
  const event = buildTriggerableEvent('hide', {cancelable: trigger !== '', trigger})

  if (
    event.defaultPrevented ||
    (trigger === 'backdrop' && noCloseOnBackdropBoolean.value) ||
    (trigger === 'esc' && noCloseOnEscBoolean.value)
  ) {
    emit('hide-prevented', event)
    return
  }

  if (trigger === 'close') {
    emit(trigger, event)
  }
  if (trigger === 'esc') {
    emit(trigger, event)
  }
  emit('hide', event)

  if (event.defaultPrevented) {
    emit('hide-prevented', event)
    return
  }

  modelValue.value = false
}

const show = () => {
  const event = buildTriggerableEvent('show', {cancelable: true})
  emit('show', event)
  if (event.defaultPrevented) {
    modelValue.value = false
    emit('show-prevented', event)
    return
  }
  modelValue.value = true
}
```

Other files suffer from a similar issue.

2023-10-19 14:42 UTC, makroxyz commented
Sorry I don't understand if this is expected or we need to fix other files too

2023-10-19 14:48 UTC, VividLemon commented
> Sorry I don't understand if this is expected or we need to fix other files too

The codeblock I gave is likely the solution you should update to. In addition, multiple other files should be fixed with that fix as well.

2023-10-19 14:54 UTC, makroxyz commented
Ok, I'm not on PC now so I thought was code from my PR I also "switched"
the if sequence.
Tomorrow I will check for other components

Il gio 19 ott 2023, 16:48 Issayah ***@***.***> ha scritto:

> Sorry I don't understand if this is expected or we need to fix other files
> too
>
> The codeblock I gave is likely the solution you should update to. In
> addition, multiple other files should be fixed with that fix as well.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/bootstrap-vue-next/bootstrap-vue-next/pull/1527#issuecomment-1771147094>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAPZLPMRXBIGVNEKUECP6VDYAE4ULAVCNFSM6AAAAAA6GWQXPGVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTONZRGE2DOMBZGQ>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-10-20 06:11 UTC, makroxyz commented
Hi I found also BModal  and fixed it.

2023-10-20 06:53 UTC, makroxyz commented
@VividLemon 

I think this is better and modal.spec.ts doesn't fail
```js
const hide = (trigger = '') => {
  const event = buildTriggerableEvent('hide', {cancelable: trigger !== '', trigger})

  if (trigger === 'ok') {
    emit(trigger, event)
  }
  if (trigger === 'cancel') {
    emit(trigger, event)
  }
  if (trigger === 'close') {
    emit(trigger, event)
  }

  if (
    event.defaultPrevented ||
    (trigger === 'backdrop' && noCloseOnBackdropBoolean.value) ||
    (trigger === 'esc' && noCloseOnEscBoolean.value)
  ) {
    emit('hide-prevented')
    return
  }

  emit('hide', event)

  modelValue.value = false
}
```

if I press close button  and I want to prevent modal close (like in test), I emit ```close``` event then close event doesn't  fire ```hide``` if prevented or ```no-close-on-backdrop```/```no-close-on-esc``` are true

the same for BOffcanvas
```js
const buildTriggerableEvent = (
  type: string,
  opts: Partial<BvTriggerableEvent> = {}
): BvTriggerableEvent =>
  new BvTriggerableEvent(type, {
    cancelable: false,
    target: element.value || null,
    relatedTarget: null,
    trigger: null,
    ...opts,
    componentId: computedId.value,
  })

const hide = (trigger = '') => {
  const event = buildTriggerableEvent('hide', {cancelable: trigger !== '', trigger})

  if (trigger === 'close') {
    emit(trigger, event)
  }
  if (trigger === 'esc') {
    emit(trigger, event)
  }

  if (
    event.defaultPrevented ||
    (trigger === 'backdrop' && noCloseOnBackdropBoolean.value) ||
    (trigger === 'esc' && noCloseOnEscBoolean.value)
  ) {
    emit('hide-prevented')
    return
  }

  emit('hide', event)

  modelValue.value = false
}
``` 
I press ESC event ```esc``` should be fired but it doesn't fire ```hide``` if prevented  or ```no-close-on-backdrop```/```no-close-on-esc``` are true

2023-10-22 01:15 UTC, VividLemon commented
> I think this is better and modal.spec.ts doesn't fail

Then fix the tests. A failing test is only an issue if the expected behavior is not correct. (Too many double negatives? If something was not correct when the test was written, then it's just a bad test!)

> if I press close button and I want to prevent modal close (like in test), I emit close event then close event doesn't fire hide if prevented or no-close-on-backdrop/no-close-on-esc are true

Let's get two things straightened out here. First off, in my code example you're able to prevent modal closing in all cases. Second off, you're misunderstanding the purpose of the hide event. It is not to indicate that the modal has been hidden, that's what the hidden event is for. Functionally it is in line with https://getbootstrap.com/docs/5.3/components/modal/#events , though our system utilizes a more extra events for specific targets. 

To add to this, the hide event also emits the Event, which allows it to be preventable. Those events are grouped up because they all signify the same point in time for the event... Assuming that makes sense. 

So, my code is in-line with what the spec is for Bootstrap v5 and how I would prefer it to be. Unless you can tell me if and how it is functionally not in compliance with the Bootstrap v5, then that is how I would prefer it to be fixed. 

Though hypothetically the 
```ts
if (
    event.defaultPrevented ||
    (trigger === 'backdrop' && noCloseOnBackdropBoolean.value) ||
    (trigger === 'esc' && noCloseOnEscBoolean.value)
  ) {
    emit('hide-prevented', event)
    return
  }
```
`event.defaultPrevented` for the first check is redundant, as you couldn't have preventedDefault yet. 

Functionally the movement of event emitting like `close` `ok`, etc is minor, but when you put it into the context of it being the same as the hide event, then I think it makes more sense. But you need to know what the purpose of the hide event is for above all else.

2023-10-23 16:58 UTC, VividLemon requested changes

2023-10-23 16:58 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BOffcanvas/BOffcanvas.vue
> +
```suggestion

if(event.defaultPrevented) {
    emit('hide-prevented')
    return
}
```

We need to ensure that you can prevent the closing when this event is triggered

2023-10-23 16:58 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BOffcanvas/BOffcanvas.vue
>      event.defaultPrevented ||
```suggestion
```
You can't prevent default at this point, so this check is unnecessary

2023-10-23 16:58 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BOffcanvas/BOffcanvas.vue
>      event.defaultPrevented ||
There might be some linting stuff to look at with this change

2023-10-23 16:58 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BModal.vue
>    }
```suggestion
  }
    emit('hide', event)
```

2023-10-23 16:58 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BModal.vue
>    }
I think the suggestion contains a linting tab issue

2023-10-23 16:58 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BModal.vue
> +  emit('hide', event)
```suggestion
```
This is moved up with the others, (close, ok, etc)

2023-10-24 06:36 UTC, makroxyz commented
Hi I commited changes but I'm not sure this is right  in both files
```js
 emit('hide', event)

  if (event.defaultPrevented) {
    emit('hide-prevented')
    return
  }
```
I emit hide before checking if it's prevented...

2023-10-24 15:26 UTC, VividLemon commented
> Hi I commited changes but I'm not sure this is right in both files
> 
> ```js
>  emit('hide', event)
> 
>   if (event.defaultPrevented) {
>     emit('hide-prevented')
>     return
>   }
> ```
> 
> I emit hide before checking if it's prevented...

Yes, that's the point. it's so you can do things like 
```html
<BModal @hide.prevent @hide-prevented="consoleLog('foo')" />
```

2023-10-25 06:27 UTC, makroxyz commented
@VividLemon 
I'm facing this issues (is it really an issue?)

When a BModal is conditioned by v-if, ```show/shown``` events are not fired. Old Bootstrap-vue does it.
I think because event are fired on BTransition tag.

```js
<template>
  <BContainer>
    <BRow>
      <BCol> 
        <BModal v-if="show" v-model="show" @show="() => console.log('show')">
          test
        </BModal>
        <BButton @click="show = true">Test</BButton>
      </BCol>
    </BRow>
  </BContainer>
</template>

<script setup lang="ts">
import { ref } from 'vue';
const show = ref(false)
</script>
````

2023-10-25 14:59 UTC, VividLemon commented
> @VividLemon I'm facing this issue
> 
> When a BModal is conditioned by v-if, `show/shown` events are not fired. Old Bootstrap-vue does it. I think because event are fired on BTransition tag.
> 
> ```js
> <template>
>   <BContainer>
>     <BRow>
>       <BCol> 
>         <BModal v-if="show" v-model="show" @show="() => console.log('show')">
>           test
>         </BModal>
>         <BButton @click="show = true">Test</BButton>
>       </BCol>
>     </BRow>
>   </BContainer>
> </template>
> 
> <script setup lang="ts">
> import { ref } from 'vue';
> const show = ref(false)
> </script>
> ```
> 
> Update: the same when a modal is used in dynamic component
> 
> ```
> <component :is="modalComponent" v-show="show" />   // fires show* event only on SECOND open since modalComponent can be undefined or null
> ```
> 
> https://vuejs.org/guide/built-ins/transition.html#the-transition-component
> 
> dynamic component or v-if component should be inside transition

This would be weird for a person to do. But regardless, I'm not sure how to fix it. Unlike attributes, directives don't fall through to $attrs. So there is no way for the component to know if a directive is attached to it (that I know of)

2023-10-25 15:03 UTC, VividLemon requested changes
This is the only remaining feedback I have.

2023-10-26 06:28 UTC, makroxyz commented
> > @VividLemon I'm facing this issue
> > When a BModal is conditioned by v-if, `show/shown` events are not fired. Old Bootstrap-vue does it. I think because event are fired on BTransition tag.
> > ```js
> > <template>
> >   <BContainer>
> >     <BRow>
> >       <BCol> 
> >         <BModal v-if="show" v-model="show" @show="() => console.log('show')">
> >           test
> >         </BModal>
> >         <BButton @click="show = true">Test</BButton>
> >       </BCol>
> >     </BRow>
> >   </BContainer>
> > </template>
> > 
> > <script setup lang="ts">
> > import { ref } from 'vue';
> > const show = ref(false)
> > </script>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Update: the same when a modal is used in dynamic component
> > ```
> > <component :is="modalComponent" v-show="show" />   // fires show* event only on SECOND open since modalComponent can be undefined or null
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > https://vuejs.org/guide/built-ins/transition.html#the-transition-component
> > dynamic component or v-if component should be inside transition
> 
> This would be weird for a person to do. But regardless, I'm not sure how to fix it. Unlike attributes, directives don't fall through to $attrs. So there is no way for the component to know if a directive is attached to it (that I know of)

That's right. But this could be a problem... I don't have any idea on how to solve it. While a v-if on a BModal should be "managed" by ```lazy``` attribute, using dynamic component isn't a bad practice and can be an issue

2023-10-27 17:19 UTC, VividLemon commented
> That's right. But this could be a problem... I don't have any idea on how to solve it. While a v-if on a BModal should be "managed" by `lazy` attribute, using dynamic component isn't a bad practice and can be an issue

You should make an issue ticket for this

2023-10-27 17:21 UTC, merged