feat(BAccordion): add class props for elements
bootstrap-vue-next/bootstrap-vue-next pull request #1537
Opened 2023-10-24 21:27 UTC by xvaara

# Describe the PR
feat(BAccordion): add class props for elements
closes #1535 

## Small replication

A small replication or video walkthrough can help demonstrate the changes made. This is optional, but can help observe the intended changes. A mentioned issue that contains a replication also works.

## PR checklist

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix :bug: - `fix(...)`
- [x] Feature - `feat(...)`
- [ ] ARIA accessibility - `fix(...)`
- [ ] Documentation update - `docs(...)`
- [ ] Other (please describe)

**The PR fulfills these requirements:**

- [x] Pull request title and all commits follow the [**Conventional Commits**](https://www.conventionalcommits.org/) convention or has an [**override**](https://github.com/googleapis/release-please#how-can-i-fix-release-notes) in this pull request body **This is very important, as the `CHANGELOG` is generated from these messages, and determines the next version type. Pull requests that do not follow conventional commits or do not have an override will be denied**

2023-10-24 21:37 UTC, VividLemon requested changes

2023-10-24 21:37 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BAccordion/BAccordionItem.vue
> +const {class: wrapperClass, ...attrs} = useAttrs()
wrapperClass could just be a prop and used in the same way. There's no reason to treat it as an attr or do anything special with useAttrs

2023-10-24 21:37 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BAccordion/BAccordionItem.vue
> +    bodyClass?: ClassValue
You should also do bodyAttrs, collapseAttrs, etc to satisfy https://github.com/orgs/bootstrap-vue-next/projects/1?pane=issue&itemId=31679414

2023-10-24 21:37 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BAccordion/BAccordionItem.vue
> +            :class="{collapsed: !toggleVisible, [buttonClass]: !!buttonClass}"
```suggestion
            :class="[buttonClass, {collapsed: !toggleVisible}]"
```

2023-10-24 21:37 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BAccordion/BAccordionItem.vue
> +            :class="{collapsed: !toggleVisible, [buttonClass]: !!buttonClass}"
Pretty sure that works the same. But smaller

2023-10-24 21:37 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BAccordion/BAccordionItem.vue
> +      v-bind="attrs"
this v-bind should probably be near the buttom. If someone were to do pass through attrs.aria-labelledby, it would always be overwritten.

2023-10-24 21:38 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BAccordion/BAccordionItem.vue
> +const {class: wrapperClass, ...attrs} = useAttrs()
In this case, it would make more sense for the attrs to all go on one element. Rather than randomly attaching to different elements.

2023-10-24 21:47 UTC, xvaara commented on packages/bootstrap-vue-next/src/components/BAccordion/BAccordionItem.vue
> +    bodyClass?: ClassValue
if we have bodyAttrs is bodyClass even needed? bodyAttrs="{class: 'bg-danger'}" would just do the "trick".

2023-10-24 21:49 UTC, xvaara commented on packages/bootstrap-vue-next/src/components/BAccordion/BAccordionItem.vue
> +const {class: wrapperClass, ...attrs} = useAttrs()
For me it would make sense for the class="foo" to go to the wrapping element (as it will go by default). That seems "correct" for me.

2023-10-24 21:54 UTC, xvaara commented on packages/bootstrap-vue-next/src/components/BAccordion/BAccordionItem.vue
> +const {class: wrapperClass, ...attrs} = useAttrs()
maybe remove inheritAttrs:false and  have the root to inherit all the attrs and have attrs-props for all the other places needed?

2023-10-24 23:10 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BAccordion/BAccordionItem.vue
> +const {class: wrapperClass, ...attrs} = useAttrs()
> For me it would make sense for the class="foo" to go to the wrapping element (as it will go by default). That seems "correct" for me.

The issue that I have is that even though it does make sense, I think the attrs inheritance should fall onto the most common component. 

Like if you were to think about from a users perspective about 
```html
<div class="form-check">
  <input class="form-check-input" type="checkbox" value="" id="flexCheckDefault">
  <label class="form-check-label" for="flexCheckDefault">
    Default checkbox
  </label>
</div>
```
The most commonly modified component would be the input. How many people actually want to affect the wrapper div? Perhaps <5%?

2023-10-25 06:45 UTC, xvaara commented on packages/bootstrap-vue-next/src/components/BAccordion/BAccordionItem.vue
> +const {class: wrapperClass, ...attrs} = useAttrs()
Sure there is a point in that for inputs. For example I might want to add margin to the wrapping with class="my-3" and it would be weird if that went to the input element.

2023-10-25 06:50 UTC, xvaara commented on packages/bootstrap-vue-next/src/components/BAccordion/BAccordionItem.vue
> +    bodyClass?: ClassValue
I changed all them to attrs and it "feels" fine. See example in the beginning.

2023-10-25 06:52 UTC, xvaara commented on packages/bootstrap-vue-next/src/components/BAccordion/BAccordionItem.vue
> +      v-bind="attrs"
you meen we want to allow user overwrite the aria-labelledby or we want to protect the user from overwriting it?

2023-10-25 14:39 UTC, VividLemon requested changes

2023-10-25 14:39 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BAccordion/BAccordionItem.vue
> +    bodyAttrs?: AttrsValue
I meant doing 
```suggestion
    headerAttrs?: AttrsValue
    headerClass?: ClassValue
    buttonAttrs?: AttrsValue
    buttonClass?: ClassValue
    collapseAttrs?: AttrsValue
    collapseClass?: ClassValue
    bodyAttrs?: AttrsValue
    bodyClass?: ClassValue
```

2023-10-25 14:40 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BAccordion/BAccordionItem.vue
> +      v-bind="attrs"
I don't really care if someone overwrites the values. That's their problem. But also their benefit as they can make it what they want

2023-10-25 14:42 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BAccordion/BAccordionItem.vue
> +    bodyClass?: ClassValue
> if we have bodyAttrs is bodyClass even needed? bodyAttrs="{class: 'bg-danger'}" would just do the "trick".

It would work just fine, but having both is simply how I'd prefer it. imo it makes it easier.

2023-10-25 14:50 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BAccordion/BAccordionItem.vue
> +const {class: wrapperClass, ...attrs} = useAttrs()
> Sure there is a point in that for inputs. For example I might want to add margin to the wrapping with class="my-3" and it would be weird if that went to the input element.

The tie breaker would be whatever element attrs falls onto in Bootstrap-vue. But that does seem somewhat strange as they inherit attrs onto the input, but the class falls into the wrapper element :thinking: Hmm. Not a great example for me. They do this quite a bit with their input elements. 

So, going off of this, lets simply say that attribute inheritance should match the behavior of Bootstrap-vue. Then we add new props to fill in the gaps. Sound good?

2023-10-25 14:53 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BAccordion/BAccordionItem.vue
> +const {class: wrapperClass, ...attrs} = useAttrs()
Keep in mind, if you were to expand this PR to fully finish https://github.com/orgs/bootstrap-vue-next/projects/1?pane=issue&itemId=31679414 , it might be a good time now since the next version to go out will be 0.15. Which still isn't going to be released for awhile, so no rush, assuming you want to do it.

2023-10-26 14:31 UTC, xvaara commented on packages/bootstrap-vue-next/src/components/BAccordion/BAccordionItem.vue
> +const {class: wrapperClass, ...attrs} = useAttrs()
So now I kinda reverted the change I made to my previous. So now the ...attrs go to BCollapse and class goes to wrapper. Should this be the "way" forward for the other components?

2023-10-26 14:45 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BAccordion/BAccordionItem.vue
> +      v-bind="{...attrs, ...collapseAttrs}"
collapseAttrs can be removed, as you should just use basic attrs

2023-10-26 14:46 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BAccordion/BAccordionItem.vue
> +  <div class="accordion-item" v-bind="wrapperAttrs" :class="[wrapperClass, directWrapperClass]">
wrapperClass can also be removed as you should just use the `directWrapperClass`

2023-10-26 14:53 UTC, xvaara commented on packages/bootstrap-vue-next/src/components/BAccordion/BAccordionItem.vue
> +      v-bind="{...attrs, ...collapseAttrs}"
I was thinking: It's not needed, but for the sake of symmetry, all the places have xxxClass and xxxAttrs, just to make sure that if some finds it confusing where the class and other attrs go. and the class and other attrs go where they go in bv2

2023-10-26 14:56 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BAccordion/BAccordionItem.vue
> +      v-bind="{...attrs, ...collapseAttrs}"
I think it should be fine. Like I said, I'd like to add this stuff to the documentation, but I don't have a plan yet on how to relay this information.

2023-10-27 15:46 UTC, xvaara commented on packages/bootstrap-vue-next/src/components/BAccordion/BAccordionItem.vue
> +      v-bind="{...attrs, ...collapseAttrs}"
is it's fine to leave or it's fine to stay? Just want to be clear on that :smile:

2023-10-27 17:18 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BAccordion/BAccordionItem.vue
> +      v-bind="{...attrs, ...collapseAttrs}"
Good to remove.

2023-10-31 16:25 UTC, merged

2023-10-31 19:39 UTC, VividLemon commented
Moving forward this will likely be the same workflow as other components for https://github.com/orgs/bootstrap-vue-next/projects/1/views/1?pane=issue&itemId=31679414 . Though, be sure that the attrs/class inheritance follows BV