docs(BModal): Update props and events
bootstrap-vue-next/bootstrap-vue-next pull request #1553
Opened 2023-11-03 19:29 UTC by dwgray

# Describe the PR

Updates all of the props and events for the BModal component.

Where possible, I copied the documentation from bootstrap-vue. I tested each property and event to ensure the documentation is consistent with the current behavior of bootstrap-vue-next.

This led to one issue - it looks like [BS5 Close Button](https://getbootstrap.com/docs/5.3/components/close-button/) does not support variants, and classes aren't passed through.  I don't see an easy way to make the code support headerCloseVariant or headerCloseClass, so I marked them as deprecated.  I would be happy to pull them out of the code, but would prefer to do that as a separate PR.

I did touch the code to make the order of the declared property defaults match the property declarations and documentation.  I don't have any strong preference for the order, so I just made everything match the order of the declarations.  But I did find it confusing when all three didn't match.  If there is a preferred order, I'm happy to move to that.

As I got into the events, I discovered that the documentation framework doesn't implement Events and Slots correctly, so I didn't continue on to documenting props.  I would be happy to create an issue to implement Events and Slots in the documentation framework if that would be helpful.  I may also have time next week to tackle that issue if no-one else if looking at it.

## Small replication

A small replication or video walkthrough can help demonstrate the changes made. This is optional but can help observe the intended changes. A mentioned issue that contains a replication also works.

## PR checklist

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix :bug: - `fix(...)`
- [ ] Feature - `feat(...)`
- [ ] ARIA accessibility - `fix(...)`
- [X] Documentation update - `docs(...)`
- [ ] Other (please describe)

**The PR fulfills these requirements:**

- [X ] Pull request title and all commits follow the [**Conventional Commits**](https://www.conventionalcommits.org/) convention or has an [**override**](https://github.com/googleapis/release-please#how-can-i-fix-release-notes) in this pull request body **This is very important, as the `CHANGELOG` is generated from these messages, and determines the next version type. Pull requests that do not follow conventional commits or do not have an override will be denied**

2023-11-03 21:47 UTC, dwgray commented
I'm new to github processes, but from what I can tell, it looks like all PRs are currently failing the ci /test-lint and ci /test-unit checks.  And I tried creating a trivial PR from my currently fully sync'd fork, and I'm getting the same failures.  If I'm missing something and I'm causing these failures, I'd appreciate a nudge in the right direction so that I can resolve the failures.

2023-11-04 03:21 UTC, VividLemon requested changes

2023-11-04 03:21 UTC, VividLemon commented on apps/docs/src/data/components/modal.data.ts
> +          description: 'Deprecated by BS V5',
You've declared this, and some other items "deprecated". But they're perfectly valid classes. Curious where you got this information

2023-11-04 03:21 UTC, VividLemon commented on apps/docs/src/data/components/modal.data.ts
>            type: 'boolean | string',
After I had saw this line, I had gone on a spree to fix up any values that were 'boolean | ${something else}'. I made a bunch of changes in https://github.com/bootstrap-vue-next/bootstrap-vue-next/pull/1555 , and this is one of them. So you may want to double check the changes you made to see if they line up with the new current values

2023-11-04 03:21 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BModal.vue
> +    contentClass: undefined,
I don't quite get what's going on here. I think you alphabetized this. But backdropVariant and autoFocusButton are at the end. Which is weird.

2023-11-04 03:21 UTC, VividLemon commented
> I'm new to github processes, but from what I can tell, it looks like all PRs are currently failing the ci /test-lint and ci /test-unit checks. And I tried creating a trivial PR from my currently fully sync'd fork, and I'm getting the same failures. If I'm missing something and I'm causing these failures, I'd appreciate a nudge in the right direction so that I can resolve the failures.

They are failing because I have some active WIP stuff regarding major BTable changes.

2023-11-04 18:30 UTC, dwgray commented on packages/bootstrap-vue-next/src/components/BModal.vue
> +    contentClass: undefined,
I noted this in the PR description, but I tend to be wordy, so I should have put it closer to the code.  This set of properties is listed three times:  1. The declaration (in the defineProps statement), 2: the default assignment (here) 3: the documentation.  I don't have any strong preference as to the order, but it was quite confusing when the declaration and the defaults were in a different order (it makes it a lot easier to verify that everything matches).  Since the order in the documentation file and the order in the definition were basically the same, I went with that and just re-arranged the defaults to match that order.  With this long a list, I think there is some argument to just make it alphabetical (that's what the user-visible version in the documentation does).  If you agree, I'm happy to do that.

2023-11-04 18:30 UTC, dwgray commented on apps/docs/src/data/components/modal.data.ts
>            type: 'boolean | string',
Okay - I'll look into that.

2023-11-04 18:35 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BModal.vue
> +    contentClass: undefined,
Alphabetize is likely the best. Though naturally when adding new properties its easy to forget.

2023-11-04 18:43 UTC, dwgray commented on apps/docs/src/data/components/modal.data.ts
> +          description: 'Deprecated by BS V5',
Just two places.  You're right on this one. I re-tested it, and it works.  I'll push a correction for that in my next round.  I'll add a comment in the other place.

2023-11-04 19:02 UTC, dwgray commented on apps/docs/src/data/components/modal.data.ts
> +          description: 'Deprecated by BS V5',
It looks like [BS5 Close Button](https://getbootstrap.com/docs/5.3/components/close-button/) does not support variants.  Setting this property does not do anything, as far as I can tell.  If I'm missing something, please let me know.  Otherwise, I'm happy to pull the code around this and remove the property from the documentation.

[StackBlitz repo](https://stackblitz.com/edit/bootstra-vue-next-template-vk45ap?file=src%2Fcomponents%2FComp.vue) or just past this into the test app.vue in the dev environment.
```
<template>
  <BButton @click="modal = !modal"> Toggle modal </BButton>
  <BModal
    v-model="modal"
    title="Testing"
    header-text-variant="danger"
    header-close-variant="danger"
    header-close-label="Custom Close"
  >
    foobar
  </BModal>
</template>

<script setup lang="ts">
import {ref} from 'vue'

const modal = ref(false)
</script>
```

2023-11-04 19:10 UTC, VividLemon commented on apps/docs/src/data/components/modal.data.ts
> +          description: 'Deprecated by BS V5',
Its a good thing you can use a slot which converts it to a regular button

2023-11-05 23:17 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BModal.vue
> +    contentClass: undefined,
You can revert your changes to the .vue file, I had alphabetized the code already. So everything should be in order there

2023-11-06 01:08 UTC, dwgray commented on packages/bootstrap-vue-next/src/components/BModal.vue
> +    contentClass: undefined,
Okay, reverted + removed the comment in the PR.

2023-11-06 01:12 UTC, dwgray commented on apps/docs/src/data/components/modal.data.ts
> +          description: 'Deprecated by BS V5',
This instance is now documented correctly.

2023-11-06 01:13 UTC, dwgray commented on apps/docs/src/data/components/modal.data.ts
>            type: 'boolean | string',
I'm happy to look into this, but I don't think I should change anything until your changes for the alphabetizing of the properties go through to avoid conflicts.  Can we let this PR go through as is and I'll look into this as a followup?

2023-11-06 01:15 UTC, dwgray commented on apps/docs/src/data/components/modal.data.ts
> +          description: 'Deprecated by BS V5',
Let me know if you would like me to pull the code that backs this and then either remove the documentation for the property or add a more detailed description of why it's deprecated (I would prefer to do the former - just clean it up) - probably more appropriate to put the deprecation in a migration document?  In any case, I don't want to touch the code until your alphabetize PR goes through, so would prefer to do this as a follow up.

2023-11-06 19:44 UTC, dwgray commented on apps/docs/src/data/components/modal.data.ts
>            type: 'boolean | string',
Sorry, I misread your comments.  I didn't realize that you touched this on Friday so I thought you wanted me to look into it, not that you had already fixed it in the code and just needed the documentation to stay in sync.  I've updated this in the documentation.

2023-11-06 19:47 UTC, dwgray commented on apps/docs/src/data/components/modal.data.ts
> +          description: 'Deprecated by BS V5',
@VividLemon Let me know how you'd like me to handle this.  I think it's the only outstanding issue on this PR.

2023-11-07 15:23 UTC, VividLemon requested changes

2023-11-07 15:23 UTC, VividLemon commented on apps/docs/src/data/components/modal.data.ts
> +            'Emitted when the modal tried to open, but was prevented from opening. THis occurs when preventDrault() is called on the event',
```suggestion
            'Emitted when the modal tried to open, but was prevented from opening. This occurs when preventDefault() is called on the event',
```

2023-11-07 15:23 UTC, VividLemon commented on apps/docs/src/data/components/modal.data.ts
> +          description: 'Deprecated by BS V5',
```suggestion
          description: 'Applies a variant to the header close button when the header close button uses the header-close slot',
```

2023-11-07 15:23 UTC, merged