docs(BButton): update component reference
bootstrap-vue-next/bootstrap-vue-next pull request #1572
Opened 2023-11-08 07:33 UTC by dploc96

# Describe the PR

Update props, events, slots of `BButton` & `BCloseButton`

## Small replication

A small replication or video walkthrough can help demonstrate the changes made. This is optional, but can help observe the intended changes. A mentioned issue that contains a replication also works.

## PR checklist

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix :bug: - `fix(...)`
- [ ] Feature - `feat(...)`
- [ ] ARIA accessibility - `fix(...)`
- [x] Documentation update - `docs(...)`
- [ ] Other (please describe)

**The PR fulfills these requirements:**

- [x] Pull request title and all commits follow the [**Conventional Commits**](https://www.conventionalcommits.org/) convention or has an [**override**](https://github.com/googleapis/release-please#how-can-i-fix-release-notes) in this pull request body **This is very important, as the `CHANGELOG` is generated from these messages, and determines the next version type. Pull requests that do not follow conventional commits or do not have an override will be denied**

2023-11-08 20:29 UTC, VividLemon requested changes

2023-11-08 20:29 UTC, VividLemon commented on apps/docs/src/data/components/button.data.ts
> +          description: `<router-link> prop: Setting append prop always appends the relative path to the current path`,
```suggestion
          description: `<RouterLink> prop: Setting append prop always appends the relative path to the current path`,
```
This suggestion goes for all components written in kebab case. **Everything** should be Pascal case

2023-11-09 01:38 UTC, dploc96 commented on apps/docs/src/data/components/button.data.ts
> +          description: `<router-link> prop: Setting append prop always appends the relative path to the current path`,
Ok thanks

2023-11-10 14:32 UTC, VividLemon commented
I'm going to close this PR in favor of https://github.com/bootstrap-vue-next/bootstrap-vue-next/pull/1580

2023-11-10 14:32 UTC, closed without merging