fix(BOverlay): fixes rounded prop #1578
bootstrap-vue-next/bootstrap-vue-next pull request #1579
Opened 2023-11-09 18:40 UTC by dwgray

# Describe the PR

This fixes a regression from PR #1555 where setting the rounded prop to false would make the overlay a rounded-circle.

## Small replication

The original PR was breaking the test overlay.spec.ts!child BTransition child div first child div has class rounded when prop rounded true.  This PR fixes that test and also extends the test that checked that the rounded class wasn't added when rounded===false to catch future regressions of this nature.

## PR checklist

**What kind of change does this PR introduce?** (check at least one)

- [X] Bugfix :bug: - `fix(...)`
- [ ] Feature - `feat(...)`
- [ ] ARIA accessibility - `fix(...)`
- [ ] Documentation update - `docs(...)`
- [ ] Other (please describe)

**The PR fulfills these requirements:**

- [X] Pull request title and all commits follow the [**Conventional Commits**](https://www.conventionalcommits.org/) convention or has an [**override**](https://github.com/googleapis/release-please#how-can-i-fix-release-notes) in this pull request body **This is very important, as the `CHANGELOG` is generated from these messages, and determines the next version type. Pull requests that do not follow conventional commits or do not have an override will be denied**

2023-11-09 18:42 UTC, dwgray commented on packages/bootstrap-vue-next/src/components/BOverlay/overlay.spec.ts
> +    // First check the explicit calsses that have caused this to break, which will give a more readable error message
I thought this was a reasonable compromise between polluting the test space, getting useful failure messages and still catching all the cases that we'd want covered.  The alternative I considered was to create three tests, one for 'rounded', one for 'rounded-circle' and a third catch-all.  Happy to move to that if you prefer.

2023-11-10 14:09 UTC, VividLemon commented
This issue was already fixed.

2023-11-10 14:10 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BOverlay/overlay.spec.ts
> +    // First check the explicit calsses that have caused this to break, which will give a more readable error message
Tests are meant to be small and test only one part of the behavior. If an item can have multiple different outputs, a unique test should be made to test each of the different outputs. 

However, in this case most of the heavy lifting is to be made as a useRadiusClasses.spec.ts test. The idea being that it is its own function and should be tested individually, as there are multiple places that use it.

2023-11-10 17:58 UTC, dwgray commented on packages/bootstrap-vue-next/src/components/BOverlay/overlay.spec.ts
> +    // First check the explicit calsses that have caused this to break, which will give a more readable error message
Fair enough.  A general expectation of one 'expect' statement per test is a reasonable bar.  I'm not seeing useRadiusClasses.spec.ts test, am I missing something?

2023-11-10 18:05 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BOverlay/overlay.spec.ts
> +    // First check the explicit calsses that have caused this to break, which will give a more readable error message
> I'm not seeing useRadiusClasses.spec.ts test

It was not made

2023-11-10 18:16 UTC, dwgray commented
> This issue was already fixed.

@VividLemon I believe this PR is still worthwhile in that it fixes and extends the test.  It is also compatible with bootstrap-vue.

You've introduced a new undocumented `none` value as the default for the rounded prop.  While I can see an argument for that being cleaner than false, anyone who used false explicitly for this prop will have to change it to none (and the way the code in main reads now, they'll get a circular overlay, which seems completely wrong).

An alternative would be to leave the existing boolean behavior in place and add `none` as an option, which is effectively what I have here.  If that works for you, I'll go ahead and document the 'none' values once this goes through.  Otherwise, I'll just go ahead and close this down, as this isn't blocking me.

2023-11-10 18:22 UTC, dwgray commented on packages/bootstrap-vue-next/src/components/BOverlay/overlay.spec.ts
> +    // First check the explicit calsses that have caused this to break, which will give a more readable error message
Okay - I think I can throw tests for useRadiusClasses together pretty easily if you think that would be useful.  Is it all right if I scaffold it and add a couple of tests in a draft PR to make sure I'm on the right track?

2023-11-10 18:36 UTC, VividLemon commented
> > This issue was already fixed.
> 
> @VividLemon I believe this PR is still worthwhile in that it fixes and extends the test. It is also compatible with bootstrap-vue.
> 
> You've introduced a new undocumented `none` value as the default for the rounded prop. While I can see an argument for that being cleaner than false, anyone who used false explicitly for this prop will have to change it to none (and the way the code in main reads now, they'll get a circular overlay, which seems completely wrong).
> 
> An alternative would be to leave the existing boolean behavior in place and add `none` as an option, which is effectively what I have here. If that works for you, I'll go ahead and document the 'none' values once this goes through. Otherwise, I'll just go ahead and close this down, as this isn't blocking me.

The issue is that the behavior modifies that of the overlay component and diverges from BV there. In BV their backdrop is a custom made implementation without the overlay component. What I noticed was that the overlay component could be expanded to the modal, and some other places, which made it possible to do some (albeit not very useful) custom stuff like adding backdrop variants to the modal. 

With that being said, I agree that the behavior is strange to have false set the value to circle. I recall seeing something in BV that did that, but it should be no class. So, as it stands I see nothing wrong with the changes in `useRadiusElementClasses.ts`, however, components that use it should likely change up their defaults. Specifically BModal 'none', should probably be false, I think bimg too.

2023-11-10 18:37 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BOverlay/overlay.spec.ts
> +    // First check the explicit calsses that have caused this to break, which will give a more readable error message
Yes

2023-11-10 19:20 UTC, dwgray commented
> > > This issue was already fixed.
> > 
> > 
> > @VividLemon I believe this PR is still worthwhile in that it fixes and extends the test. It is also compatible with bootstrap-vue.
> > You've introduced a new undocumented `none` value as the default for the rounded prop. While I can see an argument for that being cleaner than false, anyone who used false explicitly for this prop will have to change it to none (and the way the code in main reads now, they'll get a circular overlay, which seems completely wrong).
> > An alternative would be to leave the existing boolean behavior in place and add `none` as an option, which is effectively what I have here. If that works for you, I'll go ahead and document the 'none' values once this goes through. Otherwise, I'll just go ahead and close this down, as this isn't blocking me.
> 
> The issue is that the behavior modifies that of the overlay component and diverges from BV there. In BV their backdrop is a custom made implementation without the overlay component. What I noticed was that the overlay component could be expanded to the modal, and some other places, which made it possible to do some (albeit not very useful) custom stuff like adding backdrop variants to the modal.
> 
> With that being said, I agree that the behavior is strange to have false set the value to circle. I recall seeing something in BV that did that, but it should be no class. So, as it stands I see nothing wrong with the changes in `useRadiusElementClasses.ts`, however, components that use it should likely change up their defaults. Specifically BModal 'none', should probably be false, I think bimg too.

Okay - thanks for the background on that.  Makes sense to me.

BModal doesn't directly consume `useRadiusElementClasses`.  BImg and BAvatar do.  I changed BImage to `false` and BAvatar was already `false`.

2023-11-11 18:08 UTC, VividLemon commented
> > > > This issue was already fixed.
> > > 
> > > 
> > > @VividLemon I believe this PR is still worthwhile in that it fixes and extends the test. It is also compatible with bootstrap-vue.
> > > You've introduced a new undocumented `none` value as the default for the rounded prop. While I can see an argument for that being cleaner than false, anyone who used false explicitly for this prop will have to change it to none (and the way the code in main reads now, they'll get a circular overlay, which seems completely wrong).
> > > An alternative would be to leave the existing boolean behavior in place and add `none` as an option, which is effectively what I have here. If that works for you, I'll go ahead and document the 'none' values once this goes through. Otherwise, I'll just go ahead and close this down, as this isn't blocking me.
> > 
> > 
> > The issue is that the behavior modifies that of the overlay component and diverges from BV there. In BV their backdrop is a custom made implementation without the overlay component. What I noticed was that the overlay component could be expanded to the modal, and some other places, which made it possible to do some (albeit not very useful) custom stuff like adding backdrop variants to the modal.
> > With that being said, I agree that the behavior is strange to have false set the value to circle. I recall seeing something in BV that did that, but it should be no class. So, as it stands I see nothing wrong with the changes in `useRadiusElementClasses.ts`, however, components that use it should likely change up their defaults. Specifically BModal 'none', should probably be false, I think bimg too.
> 
> Okay - thanks for the background on that. Makes sense to me.
> 
> BModal doesn't directly consume `useRadiusElementClasses`. BImg and BAvatar do. I changed BImage to `false` and BAvatar was already `false`.

I was referring to BOverlay, not BModal. 'none' will work, but it should probably remain false

2023-11-13 17:30 UTC, dwgray commented
@VividLemon please hold off on looking at my latest set of changes - I misread the bootstrap documentation and was convinced that there wasn't a bare 'rounded' class, so I stripped it out.  But after I pushed these changes and went back to check the documentation to document my changes, I realized my mistake.  I'll have a corrected version up shortly.  Sorry for the confusion.

2023-11-13 17:42 UTC, dwgray commented on packages/bootstrap-vue-next/tests/composables/useRadiusElementClasses.spec.ts
> +import {useRadiusElementClasses} from '../../src/composables'
This contains (nearly) exhaustive tests for the useRadiusElementClasses rounded prop and then a single test for the ${border}rounded property to verify that they all pass through.  Since the code is shared between all the properties, this seemed reasonable to me (although I guess that makes it not completely black-box testing). Let me know if you would like additional coverage of the other properties and what kind.

2023-11-13 17:44 UTC, dwgray commented
> @VividLemon please hold off on looking at my latest set of changes - I misread the bootstrap documentation and was convinced that there wasn't a bare 'rounded' class, so I stripped it out. But after I pushed these changes and went back to check the documentation to document my changes, I realized my mistake. I'll have a corrected version up shortly. Sorry for the confusion.

Okay - that was easier than I thought.  I believe this PR is ready for review.

2023-11-13 22:14 UTC, VividLemon requested changes

2023-11-13 22:14 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BOverlay/overlay.spec.ts
> +    expect($second.classes()).not.toContain('rounded-circle')
This test doesn't assert much. Considering it could be any rounded value. Rounded false could magically make it rounded-3, yet this test wouldn't know

2023-11-13 22:14 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BOverlay/overlay.spec.ts
> +    expect($second.classes().find((str) => str.startsWith('rounded'))).toBeUndefined()
This is more of what the expected test would look like.

2023-11-13 22:14 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BOverlay/overlay.spec.ts
> +    expect($second.classes()).not.toContain('rounded-circle')
All of these small tests per component are best to be left to the composable test. The only test you'd probably need to do are, testing the default of rounded prop (rounded false, no class) and say rounded true (that it does render "something")

2023-11-14 00:34 UTC, dwgray commented on packages/bootstrap-vue-next/src/components/BOverlay/overlay.spec.ts
> +    expect($second.classes()).not.toContain('rounded-circle')
> This test doesn't assert much. Considering it could be any rounded value. Rounded false could magically make it rounded-3, yet this test wouldn't know

Sorry, I'm not sure how this crept in.  I agree that this and the test above `child BTransition child div first child div does not have class rounded when prop rounded false` (which I didn't write) are fairly worthless, which is why I wrote the next test which asserts something stronger.  I'd like to delete this test and the one that assert .not.toContain('rounded').

2023-11-14 00:37 UTC, dwgray commented on packages/bootstrap-vue-next/src/components/BOverlay/overlay.spec.ts
> +    expect($second.classes()).not.toContain('rounded-circle')
> All of these small tests per component are best to be left to the composable test. The only test you'd probably need to do are, testing the default of rounded prop (rounded false, no class) and say rounded true (that it does render "something")

Sorry - this and the other test you objected to crept in when I did a cherry-pick from a different branch.  I though I ran through the code after I did that, but didn't do a thorough enough job.  I'll fix this up.

2023-11-14 00:51 UTC, dwgray commented on packages/bootstrap-vue-next/src/components/BOverlay/overlay.spec.ts
> +    expect($second.classes()).not.toContain('rounded-circle')
Okay - I've trimmed this to two tests at this level: Rounded=true, Rounded=false.  I agree that the composable tests I've added provide sufficient coverage for the rest.

2023-11-14 18:01 UTC, VividLemon commented
gw

2023-11-14 18:02 UTC, merged