Floating size, overflow and boundary features and fixes.
bootstrap-vue-next/bootstrap-vue-next pull request #1614
Opened 2023-11-21 14:05 UTC by xvaara

# Describe the PR

fix(BDropdown): fix dropup prop ignored
feat(BDropdown): overflow auto and sizing middleware to limit the size to visible viewport
feat(BPopover): overflow auto and sizing middleware to limit the size to visible viewport
feat(BDropdown): add boundaryPadding prop
feat(BPopover): add boundaryPadding prop
feat(BPopover): add boundary prop
fix(BPopover): hide not working

## Small replication

A small replication or video walkthrough can help demonstrate the changes made. This is optional, but can help observe the intended changes. A mentioned issue that contains a replication also works.

## PR checklist

**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix :bug: - `fix(...)`
- [x] Feature - `feat(...)`
- [ ] ARIA accessibility - `fix(...)`
- [ ] Documentation update - `docs(...)`
- [ ] Other (please describe)

**The PR fulfills these requirements:**

- [x] Pull request title and all commits follow the [**Conventional Commits**](https://www.conventionalcommits.org/) convention or has an [**override**](https://github.com/googleapis/release-please#how-can-i-fix-release-notes) in this pull request body **This is very important, as the `CHANGELOG` is generated from these messages, and determines the next version type. Pull requests that do not follow conventional commits or do not have an override will be denied**

2023-11-22 15:20 UTC, VividLemon requested changes

2023-11-22 15:20 UTC, VividLemon commented on apps/playground/src/components/Comps/TPopover.vue
> +          <div v-for="(_, i) in Array(200)" :key="i">foobar {{ i }}</div>
```suggestion
          <div v-for="i in 200" :key="i">foobar {{ i }}</div>
```
Should be valid syntax. Not that I'm super picky on the test environments, just trying to teach you about it if you didn't know about it

2023-11-22 15:20 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BDropdown/BDropdown.vue
> +const sizeStyles = ref<{maxHeight?: string; maxWidth?: string}>({})
```suggestion
const sizeStyles = ref<StyleValue>({})
```
This should work better

2023-11-22 15:20 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BPopover.vue
> +const sizeStyles = ref<{maxHeight?: string; maxWidth?: string}>({})
Same as above

2023-11-22 21:28 UTC, xvaara commented on apps/playground/src/components/Comps/TPopover.vue
> +          <div v-for="(_, i) in Array(200)" :key="i">foobar {{ i }}</div>
oh, didn't know that, thanks! 😄

2023-11-23 00:01 UTC, xvaara commented on packages/bootstrap-vue-next/src/components/BDropdown/BDropdown.vue
> +const sizeStyles = ref<{maxHeight?: string; maxWidth?: string}>({})
That gave me error: Type instantiation is excessively deep and possibly infinite.
CSSProperties worked.

2023-11-23 14:10 UTC, merged