feat(BTable): Make BTable and BTableLite Generic components
bootstrap-vue-next/bootstrap-vue-next pull request #1681
Opened 2023-12-18 01:15 UTC by dwgray

# Describe the PR

A clear and concise description of what the pull request does.

## Small replication

The underlying types for TableItem and TableField have generic variants, but in order to fully utilize them, I believe you have to make BTable and BTable lite generic components.  This is my first crack at making that change, it doesn't currently work, so I'm going to step back and do some more exploration of how generic components work to see if I can figure out what I'm missing.  If anyone has ideas on what I might be missing (or if I'm going down the wrong path) I'd appreciate feedback.

## PR checklist

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix :bug: - `fix(...)`
- [X] Feature - `feat(...)`
- [ ] ARIA accessibility - `fix(...)`
- [ ] Documentation update - `docs(...)`
- [ ] Other (please describe)

**The PR fulfills these requirements:**

- [X] Pull request title and all commits follow the [**Conventional Commits**](https://www.conventionalcommits.org/) convention or has an [**override**](https://github.com/googleapis/release-please#how-can-i-fix-release-notes) in this pull request body **This is very important, as the `CHANGELOG` is generated from these messages, and determines the next version type. Pull requests that do not follow conventional commits or do not have an override will be denied**

2023-12-24 21:50 UTC, dwgray commented on packages/bootstrap-vue-next/src/components/BTable/BTableLite.vue
> +              :variant="item._cellVariants?.[field.key as keyof T] ? null : field.variant"
I'm having to explictly narrow the field.key to String in some places and keyof T in others.  I'm not sure if there is a cleaner way to handle that.

2023-12-24 21:52 UTC, dwgray commented on packages/bootstrap-vue-next/src/components/BTable/BTable.vue
> +}) as Ref<TableItem<T>[]>
Without the explicit cast here, references to selectedItemsModel.value generate an error:  

```
'TableItem<T>' is not assignable to parameter of type 'UnwrapRefSimple<TableItem<T>>'
```

2023-12-24 21:54 UTC, dwgray commented on packages/bootstrap-vue-next/src/components/BTable/BTable.vue
> +const internalItems = ref<TableItem<T>[]>([]) as Ref<TableItem<T>[]>
Without the explicit cast, references to internaItems generate an error:

```
Type 'TableItem<T>' is not assignable to type 'UnwrapRefSimple<TableItem<T>>'
```

2023-12-24 21:55 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BTable/BTable.vue
> +}) as Ref<TableItem<T>[]>
It's possible Vueuse's initial implementation didn't account for the fact that props would ever be capable of being generic

2023-12-24 21:57 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BTable/BTable.vue
> +const internalItems = ref<TableItem<T>[]>([]) as Ref<TableItem<T>[]>
was this wrong https://github.com/bootstrap-vue-next/bootstrap-vue-next/pull/1681#discussion_r1435883369 and Vue is to blame?! :monocle_face:

2023-12-24 22:30 UTC, dwgray commented
@VividLemon I'm attempting to merge your readonly changes into this branch and am getting linter errors on files that I haven't touched.

```
C:\Projects\bootstrap-vue-next\packages\bootstrap-vue-next\src\components\BFormSelect\BFormSelectOptionGroup.vue
  38:20  error  Type of the default value for 'options' prop must be a object  vue/require-valid-default-prop

C:\Projects\bootstrap-vue-next\packages\bootstrap-vue-next\src\components\BFormSpinbutton\BFormSpinbutton.vue
  13:18  error  Filters are deprecated  vue/no-deprecated-filter
  56:18  error  Filters are deprecated  vue/no-deprecated-filter
```

Any thoughts on what could be going on?

2023-12-24 23:10 UTC, VividLemon commented
> @VividLemon I'm attempting to merge your readonly changes into this branch and am getting linter errors on files that I haven't touched.
> 
> ```
> C:\Projects\bootstrap-vue-next\packages\bootstrap-vue-next\src\components\BFormSelect\BFormSelectOptionGroup.vue
>   38:20  error  Type of the default value for 'options' prop must be a object  vue/require-valid-default-prop
> 
> C:\Projects\bootstrap-vue-next\packages\bootstrap-vue-next\src\components\BFormSpinbutton\BFormSpinbutton.vue
>   13:18  error  Filters are deprecated  vue/no-deprecated-filter
>   56:18  error  Filters are deprecated  vue/no-deprecated-filter
> ```
> 
> Any thoughts on what could be going on?

If its not coming from your project, its fine. I'll fix it later. I suppose I should be more conscious of others working on stuff. I'm not used to having a few people adding prs

2023-12-25 00:52 UTC, VividLemon commented on packages/bootstrap-vue-next/src/App.vue
> +          <!-- TODO: is typing of dynamic slots possible? -->
No

2023-12-25 00:52 UTC, VividLemon commented on packages/bootstrap-vue-next/src/App.vue
> +          <!-- TODO: is typing of dynamic slots possible? -->
Ts limitation

2023-12-25 00:58 UTC, dwgray commented on packages/bootstrap-vue-next/src/components/BTable/BTable.vue
> +const internalItems = ref<TableItem<T>[]>([]) as Ref<TableItem<T>[]>
My guess is that vue is to blame.  If I have time, I'll see if I can create an isolated repro of this to call it out to the vue core team - but I don't think this blocks the intent of this PR, since it doesn't affect the DX of the consumer of the library.

2023-12-25 01:04 UTC, dwgray commented on packages/bootstrap-vue-next/src/App.vue
> +          <!-- TODO: is typing of dynamic slots possible? -->
Okay - I just removed the comment.

2023-12-25 01:07 UTC, dwgray commented
> > @VividLemon I'm attempting to merge your readonly changes into this branch and am getting linter errors on files that I haven't touched.
> > ```
> > C:\Projects\bootstrap-vue-next\packages\bootstrap-vue-next\src\components\BFormSelect\BFormSelectOptionGroup.vue
> >   38:20  error  Type of the default value for 'options' prop must be a object  vue/require-valid-default-prop
> > 
> > C:\Projects\bootstrap-vue-next\packages\bootstrap-vue-next\src\components\BFormSpinbutton\BFormSpinbutton.vue
> >   13:18  error  Filters are deprecated  vue/no-deprecated-filter
> >   56:18  error  Filters are deprecated  vue/no-deprecated-filter
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Any thoughts on what could be going on?
> 
> If its not coming from your project, its fine. I'll fix it later. I suppose I should be more conscious of others working on stuff. I'm not used to having a few people adding prs
> 
> [#1698 (comment)](https://github.com/bootstrap-vue-next/bootstrap-vue-next/issues/1698#issuecomment-1868609813)

Okay - I completed the merge. I think this PR is ready, unless you've got ideas on the String/keyof T casts that I'm doing.

2023-12-25 05:25 UTC, VividLemon requested changes

2023-12-25 05:25 UTC, VividLemon commented on packages/bootstrap-vue-next/src/App.vue
> -// Please do not commit this file
Just this

2023-12-25 18:52 UTC, merged

2023-12-25 18:56 UTC, dwgray commented on packages/bootstrap-vue-next/src/App.vue
> -// Please do not commit this file
Sorry about that.  I have reverted those changes.

2024-01-04 22:49 UTC, dwgray commented on packages/bootstrap-vue-next/src/components/BTable/BTable.vue
> +const internalItems = ref<TableItem<T>[]>([]) as Ref<TableItem<T>[]>
> was this wrong [#1681 (comment)](https://github.com/bootstrap-vue-next/bootstrap-vue-next/pull/1681#discussion_r1435883369) and Vue is to blame?! 🧐

I just got back to this and found https://github.com/vuejs/core/issues/2136#issuecomment-693524663, which seems to explain the behavior, so I think I'm good with leaving it as is.