BModal emits show and hide more than once
bootstrap-vue-next/bootstrap-vue-next pull request #1693
Opened 2023-12-22 19:48 UTC by anrolmar

# Describe the PR

Emits show event only once when the modal is shown
emits hide event only once when the modal is dismissed

## Small replication

https://github.com/corymccarty/bootstrap-vue-next-modal-emits

## PR checklist

**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix :bug: - `fix(...)`
- [ ] Feature - `feat(...)`
- [ ] ARIA accessibility - `fix(...)`
- [ ] Documentation update - `docs(...)`
- [ ] Other (please describe)

**The PR fulfills these requirements:**

- [x] Pull request title and all commits follow the [**Conventional Commits**](https://www.conventionalcommits.org/) convention or has an [**override**](https://github.com/googleapis/release-please#how-can-i-fix-release-notes) in this pull request body **This is very important, as the `CHANGELOG` is generated from these messages, and determines the next version type. Pull requests that do not follow conventional commits or do not have an override will be denied**

2023-12-24 01:07 UTC, VividLemon commented
It's probably worthwhile to figure out _whos_ calling the showFn, to see who/why it's being called twice.

2023-12-24 10:13 UTC, anrolmar commented
It's calling twice, because showFn is calling in the `onBeforeEnter` and in the `watcher`:

`const onBeforeEnter = () => showFn()`

```
watch(modelValueBoolean, (newValue, oldValue) => {
  if (newValue === oldValue) return
  if (newValue === true) {
    showFn()
  } else {
    hide()
  }
})
```

On the other hand, we have the onAfterEnter event:

```
const onAfterEnter = () => {
  isActive.value = true
  pickFocusItem()
  emit('shown', buildTriggerableEvent('shown'))
  if (lazyBoolean.value === true) lazyLoadCompleted.value = true
}
```

The watcher is executed on the `onAfterEnter` because `modelValueBoolean` is binded with the `isActive` value, and it's set on the onAfterEnter.

That's the reason I added a rule on the showFn method to check if the modal was activated or not:

```
const showFn = () => {
  if (!isActive.value) {
    const event = buildTriggerableEvent('show', {cancelable: true})
    emit('show', event)
    if (event.defaultPrevented) {
      if (modelValue.value) modelValue.value = false
      emit('show-prevented')
      return
    }

    if (!modelValue.value) modelValue.value = true
  }
}
```

2024-01-07 19:21 UTC, VividLemon commented
How does one create a PR with 0 file changes?

2024-01-07 20:47 UTC, anrolmar commented
My changes were removing in this commit, https://github.com/bootstrap-vue-next/bootstrap-vue-next/pull/1693/commits/7bea51c1fc3c56ef8c0c34498bd97471c98d30c1 when I merged from the main branch.

They're on the current PR, again

2024-01-12 22:14 UTC, VividLemon requested changes

2024-01-12 22:14 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BModal/BModal.vue
> +  if (!isActive.value) {
```suggestion
  if (isActive.value) return
```

Modify the logic to return early if the condition isn't met. Just makes nested lines cleaner

2024-01-14 21:59 UTC, merged