fix(): Remove @input in favor of @update:modelValue
bootstrap-vue-next/bootstrap-vue-next pull request #1696
Opened 2023-12-23 20:57 UTC by anrolmar

# Describe the PR

Change @input for @update:modelValue event in BFormCheckbox, BFormCheckboxGroup, BFormRadio, BFormRadioGroup, BFormSelect, BFormTags and useFormInput

fix #1657

## Small replication

## PR checklist

**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix :bug: - `fix(...)`
- [ ] Feature - `feat(...)`
- [ ] ARIA accessibility - `fix(...)`
- [ ] Documentation update - `docs(...)`
- [ ] Other (please describe)

**The PR fulfills these requirements:**

- [x] Pull request title and all commits follow the [**Conventional Commits**](https://www.conventionalcommits.org/) convention or has an [**override**](https://github.com/googleapis/release-please#how-can-i-fix-release-notes) in this pull request body **This is very important, as the `CHANGELOG` is generated from these messages, and determines the next version type. Pull requests that do not follow conventional commits or do not have an override will be denied**

2023-12-23 21:23 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BFormCheckbox/BFormCheckbox.vue
> +      @input="modelValue !== undefined && emit('update:modelValue', modelValue)"
So there is some additional complexity to this issue that isn't spoken about in the issue.

The goal is to not treat change or inputs with any specialty. The input event should just be the native input event. In Vue 2, this wasn't possible because the native input event became the modelValue. In Vue 3, we have a custom modelValue/update:modelValue event

So, what we _actually_ want is to just emit the natural value. 

**However**, if the input is not the root component, it doesn't trigger the event upwards. Since this is not the root component, we wouldn't emit it if we just excluded line 21 & 22. 

What we actually want to do instead is simply 

```html
     @change="emit('change', $event)"
     @input="emit('input', $event)"
```
This is what we want to do when the input is not the root component, when it is the root component, we simply exclude the lines and don't treat them with any particular importance. 

This is applied to all input bearing components

2023-12-24 16:41 UTC, VividLemon requested changes

2023-12-24 16:41 UTC, VividLemon commented on .release-please-manifest.json
> +  "packages/bootstrap-vue-next": "0.16.0",
Revert this file

2023-12-24 16:41 UTC, VividLemon commented on packages/bootstrap-vue-next/CHANGELOG.md
> +## [0.16.0](https://github.com/bootstrap-vue-next/bootstrap-vue-next/compare/bootstrapvuenext-v0.15.5...bootstrapvuenext-v0.16.0) (2023-12-24)
(and so on)

2023-12-24 16:41 UTC, VividLemon commented on package.json
> +    "lint-staged": "^15.0.2",
(and so on)

2023-12-24 16:41 UTC, VividLemon commented on apps/playground/tsconfig.app.json
> +  "extends": ["@vue/tsconfig/tsconfig.dom.json", "@vue/tsconfig/tsconfig.lib.json"],
Revert this.

You can ignore any of the issues. I will fix them later

2023-12-24 16:41 UTC, VividLemon commented on apps/playground/tsconfig.node.json
> +    "@tsconfig/node20/tsconfig.json",
(and so on)

2023-12-24 16:41 UTC, VividLemon commented on packages/bootstrap-vue-next/package.json
> +  "version": "0.16.0",
(and so on)

2023-12-24 16:41 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BFormCheckbox/BFormCheckbox.vue
> +  input: [event: Event]
```suggestion
  input: [event: Event]
  'update:modelValue': [value: CheckboxValue | CheckboxValue[]]
```
The model value update is still required

2023-12-24 16:41 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BFormRadio/BFormRadio.vue
> +  input: [value: Event]
```suggestion
  input: [value: Event]
  'update:modelValue': [value: RadioValue]
```

2023-12-24 16:41 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BFormRadio/BFormRadioGroup.vue
> +  emit('update:modelValue', newValue)
In this you're updating the model value to its same value, when the model value changes. It's circular and will likely cause an infinite loop.

Regardless, in the case of "Group" components, the input/change events are custom implementations, and can stay. So, this file, and the BFormSelectOptionGroup can stay the way they are

2023-12-24 16:41 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BFormSelect/BFormSelectOptionGroup.vue
> +    // eslint-disable-next-line vue/require-valid-default-prop
You can revert this file, I will take a look at this issue later. I'd like to figure out why it's failing -- although it's likely just a vue-eslint problem

2023-12-24 16:41 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BFormSpinbutton/BFormSpinbutton.vue
> +    <slot :name="`${slotName as 'increment' | 'decrement'}`" :has-focus="focused">
The changes here are wrong. One of these slots is for the top and the other is for the bottom. They are not the same. So, this file can be reverted. I'm not sure why it was changed.

2023-12-24 16:41 UTC, VividLemon commented on packages/bootstrap-vue-next/src/composables/useBooleanish.ts
> +/* eslint-disable no-console */
Revert this file change. The previous code is how it is supposed to be

2023-12-24 16:41 UTC, VividLemon commented on packages/bootstrap-vue-next/tests/composables/useBooleanish.spec.ts
> +/* eslint-disable no-console */
```suggestion
```

2023-12-24 16:41 UTC, VividLemon commented on packages/nuxt/CHANGELOG.md
> +## [0.16.0](https://github.com/bootstrap-vue-next/bootstrap-vue-next/compare/nuxt-v0.15.5...nuxt-v0.16.0) (2023-12-24)
This file can be reverted. Not sure how this was applied, but 0.16 is not released yet

2023-12-24 16:41 UTC, VividLemon commented on packages/nuxt/package.json
> +  "version": "0.16.0",
Revert

2023-12-24 16:41 UTC, VividLemon commented on pnpm-lock.yaml
> +        specifier: ^15.0.2
Revert

2023-12-25 09:10 UTC, anrolmar commented on .release-please-manifest.json
> +  "packages/bootstrap-vue-next": "0.16.0",
Done

2023-12-25 09:20 UTC, anrolmar commented on packages/bootstrap-vue-next/src/components/BFormSpinbutton/BFormSpinbutton.vue
> +    <slot :name="`${slotName as 'increment' | 'decrement'}`" :has-focus="focused">
Because I had some compiling errors (#1698)

2023-12-25 19:02 UTC, anrolmar commented
The PR failed because the same errors as https://github.com/bootstrap-vue-next/bootstrap-vue-next/pull/1681#issuecomment-1868609339

2023-12-27 01:18 UTC, VividLemon commented
You should be able to pull in the main branch now and clear out anything that doesn't need to be changed.

2024-01-02 16:57 UTC, VividLemon requested changes
You are missing changes to BFormInput (the defineEmits needs to be changed, the actual emitting is done in useFormInput)

2024-01-02 16:57 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BFormSpinbutton/BFormSpinbutton.vue
> +    <slot :name="(buttons.top.slot.name as 'increment' | 'decrement')" :has-focus="focused">
Revert the changes in this file

2024-01-02 16:57 UTC, VividLemon commented on packages/bootstrap-vue-next/CHANGELOG.md
>  # Changelog
Revert the changes in this file

2024-01-03 21:21 UTC, xvaara commented
@VividLemon Are these emits/v-on:xx even needed? Couldn't we just bind attrs to the form element? Or then typescript wouldn't maybe have completion for the events?

2024-01-04 01:14 UTC, VividLemon commented
> @VividLemon Are these emits/v-on:xx even needed? Couldn't we just bind attrs to the form element? Or then typescript wouldn't maybe have completion for the events?

The component is a fragment so it won't bubble up without declaring it. Feel free to try it out without explicitly declaring it, AFAIK it shouldn't work

2024-01-22 02:33 UTC, VividLemon commented
I'll be looking at this soon. Its been sitting too long lol 🙏

2024-01-22 10:17 UTC, anrolmar commented
Because, it seems to have a lot of comments, could you tell me what it needs to be done?

2024-01-23 16:50 UTC, VividLemon requested changes
Then finally, the implementation of useFormInput needs to change its emitted events to be the Event in the onChange/onInput methods of that composable

2024-01-23 16:50 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BFormInput/BFormInput.vue
> +  'blur': [val: any]
This is still likely a FocusEvent

2024-01-23 16:50 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BFormInput/BFormInput.vue
>    'change': [val: any]
This input & change are going to be `Event`

2024-01-23 16:50 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BFormInput/BFormInput.vue
>    'change': [val: any]
This probably applies to BFormTextarea as well

2024-01-23 16:50 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BFormSelect/BFormSelectOptionGroup.vue
>  </template>
File `BFormSelect` needs to change its implementation of change/input. 
![image](https://github.com/bootstrap-vue-next/bootstrap-vue-next/assets/31498096/06cea10a-8f2a-4e32-8fef-0a3c02f60899)
Can be changed to remove input/change
and then it needs to  be added to the select element

```html
<select @input="emit('input', $event)" @change="emit('change', $event) />
```

2024-01-26 20:07 UTC, anrolmar commented
The PR is failing because some unit testing related to the BFormCheckbox. Maybe because this PR, https://github.com/bootstrap-vue-next/bootstrap-vue-next/pull/1725

2024-01-27 23:22 UTC, VividLemon commented
> The PR is failing because some unit testing related to the BFormCheckbox. Maybe because this PR, #1725

You accidentally messed up a merge conflict. You have 40 files changed

2024-01-28 00:36 UTC, merged