fix(utils): make useId SSR friendly
bootstrap-vue-next/bootstrap-vue-next pull request #1731
Opened 2024-01-26 13:15 UTC by Al-Rozhkov

# Describe the PR

If component id is not explicitly specified, it is generated using Math.random(), which leads to hydration errors:

```
Hydration attribute mismatch on <input id=​"__BVID__921175___BV_form-check__" class=​"form-check-input" type=​"checkbox">​ 
  - rendered on server: id="__BVID__921175___BV_form-check__"
  - expected on client: id="__BVID__935395___BV_form-check__"
```

Solution: use the bootstrap-vue strategy. If the component id is not specified, leave it empty during SSR and generate it `onMounted`.

Fixes: https://github.com/bootstrap-vue-next/bootstrap-vue-next/issues/1730

## Small replication

A small replication or video walkthrough can help demonstrate the changes made. This is optional, but can help observe the intended changes. A mentioned issue that contains a replication also works.

## PR checklist

**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix :bug: - `fix(...)`
- [ ] Feature - `feat(...)`
- [ ] ARIA accessibility - `fix(...)`
- [ ] Documentation update - `docs(...)`
- [ ] Other (please describe)

**The PR fulfills these requirements:**

- [x] Pull request title and all commits follow the [**Conventional Commits**](https://www.conventionalcommits.org/) convention or has an [**override**](https://github.com/googleapis/release-please#how-can-i-fix-release-notes) in this pull request body **This is very important, as the `CHANGELOG` is generated from these messages, and determines the next version type. Pull requests that do not follow conventional commits or do not have an override will be denied**

2024-01-28 01:34 UTC, VividLemon requested changes
I'll need to think about this. While fixing a different issue for SSR, you've also introduced a https://vuejs.org/guide/scaling-up/ssr.html#cross-request-state-pollution

2024-01-29 07:13 UTC, Al-Rozhkov commented
Thank you for quick reply. I've fixed debugger.

If no `id` is specified, it remains empty on the server (just like with bootstrap-vue). `getId` function is called only client side, so no chance for Cross-Request State Pollution.

Please indicate what other issues you see here.

2024-01-30 15:48 UTC, darthf1 commented
Nuxt 3.10 just released with an SSR friendly `useId` [composable](https://github.com/nuxt/nuxt/pull/23368) 

For Non-Nuxt users, something [similar](https://github.com/vuejs/rfcs/discussions/557) is expected in [Vue 3.5](https://twitter.com/youyuxi/status/1745379112456429688) (but i dont know the timetable).

2024-01-31 16:04 UTC, VividLemon approved these changes

2024-02-01 03:53 UTC, VividLemon commented
Just gotta fix those issues then I'll merge

2024-02-15 15:50 UTC, Al-Rozhkov commented
I've fixed tests. Please, review again.

2024-02-16 14:48 UTC, VividLemon submitted a review, later dismissed

2024-02-21 14:36 UTC, Al-Rozhkov commented
I double checked build. It should be green now.

2024-02-21 19:15 UTC, VividLemon commented
Depending on the outcome of Vue 3.5, we may have a builtin composable for this 👀 Perhaps we should simply wait for the official tool first? (With high hopes I suppose, 3.5 may or may not include that change. I'm not mind reader)

It's up to you though. It just looks like a lot of this code is a bit hacky. (nextTicks here and there waiting for things to happen 🤮) I assume the official Vue version would implement SSR protection (as if it didn't, then there would be no actual need for the composable). Idk, just seems like a lot to have a stable id rn

2024-04-03 21:33 UTC, VividLemon commented
Closing in favor of https://github.com/bootstrap-vue-next/bootstrap-vue-next/pull/1836

2024-04-03 21:33 UTC, closed without merging