feat(BTable): Enable more sorting options to get closer to BSV parity
bootstrap-vue-next/bootstrap-vue-next pull request #1771
Opened 2024-02-14 20:14 UTC by dwgray

# Describe the PR

There were a few issues with table sorting compared to BSV:
- The sortDesc flag wasn't respected
- The sortByFormatted field wasn't used
    - And the sortByFormatted field didn't allow passing in a formatter function

I also added tests to cover these cases and updated the type documentation.

## Small replication

Any sorted table example will replicate these issues.  See the tests in this PR for concrete examples.

## PR checklist

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix :bug: - `fix(...)`
- [x] Feature - `feat(...)`
- [ ] ARIA accessibility - `fix(...)`
- [x] Documentation update - `docs(...)`
- [ ] Other (please describe)

**The PR fulfills these requirements:**

- [X] Pull request title and all commits follow the [**Conventional Commits**](https://www.conventionalcommits.org/) convention or has an [**override**](https://github.com/googleapis/release-please#how-can-i-fix-release-notes) in this pull request body **This is very important, as the `CHANGELOG` is generated from these messages, and determines the next version type. Pull requests that do not follow conventional commits or do not have an override will be denied**

2024-02-19 18:47 UTC, VividLemon requested changes

2024-02-19 18:47 UTC, VividLemon commented on packages/bootstrap-vue-next/src/utils/formatItem.ts
> +import type {TableFieldFormatter, TableItem} from 'src/types'
You won't be able to import from 'src/types'. It needs to be a relative path (types generation for library consumption breaks, even though it appears to work correctly here)

2024-02-19 18:55 UTC, dwgray commented on packages/bootstrap-vue-next/src/utils/formatItem.ts
> +import type {TableFieldFormatter, TableItem} from 'src/types'
Okay, thanks.  I changed this to a relative path.  Is there a way for me to check type generation in the future (other than just knowing to use relative paths)?

2024-02-19 20:26 UTC, VividLemon submitted a review, later dismissed

2024-02-21 16:02 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BTable/BTable.vue
> -    return sortDescBoolean.value && props.sortCompare === undefined ? sorted.reverse() : sorted
I assume this functionality still is working in `return (
        realVal(a).localeCompare(realVal(b), props.sortCompareLocale, props.sortCompareOptions) *
        (sortDescBoolean.value ? -1 : 1)`

2024-02-21 16:02 UTC, VividLemon approved these changes

2024-02-21 16:25 UTC, dwgray commented on packages/bootstrap-vue-next/src/components/BTable/BTable.vue
> -    return sortDescBoolean.value && props.sortCompare === undefined ? sorted.reverse() : sorted
Yes - we had a case "conflicting" PRs that solved the same problem in ways that didn't _actually_ cause a conflict in the diffs.  My unit tests caught this. I left the way that I solved it in, as I think it's slightly cleaner (but I'm not a native JS developer, so if you'd prefer doing the explicit reverse at the end rather than sorting in the correct direction in the first place, I'll swap it out.

2024-02-21 18:19 UTC, VividLemon approved these changes

2024-02-21 18:20 UTC, merged