chore: remove Booleanish type and useBooleanish composable
bootstrap-vue-next/bootstrap-vue-next pull request #1791
Opened 2024-02-22 10:50 UTC by sceee

# Describe the PR

BREAKING CHANGE: remove Booleanish type and useBooleanish composable, replace by plain boolean type

Closes: #1774

## Small replication

n/a

## PR checklist

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix :bug: - `fix(...)`
- [ ] Feature - `feat(...)`
- [ ] ARIA accessibility - `fix(...)`
- [ ] Documentation update - `docs(...)`
- [x] Other (please describe)

**The PR fulfills these requirements:**

- [x] Pull request title and all commits follow the [**Conventional Commits**](https://www.conventionalcommits.org/) convention or has an [**override**](https://github.com/googleapis/release-please#how-can-i-fix-release-notes) in this pull request body **This is very important, as the `CHANGELOG` is generated from these messages, and determines the next version type. Pull requests that do not follow conventional commits or do not have an override will be denied**

2024-02-22 16:51 UTC, VividLemon requested changes

2024-02-22 16:51 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BAccordion/BAccordion.vue
> +const freeBoolean = computed(() => props.free)
With this change, you don't need to declare these values. Instead, you should just be able to use the prop directly. So, in places where you have `*prop*Boolean = ...` just remove those variables entirely please

2024-02-22 16:51 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BAlert/BAlert.vue
> +const dismissibleBoolean = computed(() => props.dismissible)
It really goes for everything

2024-02-22 16:51 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BCol.vue
> +    col: {type: [Boolean, String] as PropType<boolean>, default: false}, // Generic flexbox .col (xs)
```suggestion
    col: {type: Boolean, default: false}, // Generic flexbox .col (xs)
```

2024-02-22 16:51 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BDropdown/BDropdown.vue
> +    modelValue.value = !modelValueBoolean.value
😲 Is that a bug fix I see?

2024-02-22 16:51 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BFormGroup/BFormGroup.vue
> +    disabled: {type: [Boolean, String] as PropType<boolean>, default: false},
```suggestion
    disabled: {type: Boolean, default: false},
```

2024-02-22 16:51 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BFormGroup/BFormGroup.vue
> +    tooltip: {type: [Boolean, String] as PropType<boolean>, default: false},
```suggestion
    labelSrOnly: {type: Boolean, default: false},
    state: {type: Boolean as PropType<boolean | null>, default: null},
    tooltip: {type: Boolean, default: false},
```

`state: {type: Boolean as PropType<boolean | null>, default: null},` probably has some alternative syntax that doesn't use `PropType`

2024-02-22 16:51 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BFormGroup/BFormGroup.vue
> +    floating: {type: [Boolean, String] as PropType<boolean>, default: false},
```suggestion
    validated: {type: Boolean, default: false},
    floating: {type: Boolean, default: false},
```

2024-02-22 16:51 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BFormInput/BFormInput.vue
> +      // noWheel: {type: [Boolean, String] as PropType<boolean>, default: false}, TODO: not implemented yet
```suggestion
      // noWheel: {type: Boolean, default: false}, TODO: not implemented yet
```

2024-02-22 16:51 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BLink/BLink.vue
> +  // prefetch: {type: [Boolean, String] as PropType<boolean>, default: null},
```suggestion
  // noPrefetch: {type: Boolean, default: false},
  // prefetch: {type: Boolean, default: null},
```

2024-02-22 16:51 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BNavbar/BNavbar.vue
> +    container?: 'fluid' | boolean | Breakpoint
```suggestion
    container?: boolean | 'fluid' | Breakpoint
```

(Fixes a preexisting bug)

If you find any prop definitions that are similar to this, you want to make sure `boolean` comes first. Read https://vuejs.org/guide/components/props.html#boolean-casting 

If you don't mind, please take a browse through the props definitions and make sure boolean comes first

2024-02-22 16:51 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BRow.vue
> +    noGutters: {type: [Boolean, String] as PropType<boolean>, default: false},
```suggestion
    noGutters: {type: Boolean, default: false},
```

2024-02-22 16:51 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BTabs/BTab.vue
> +const lazyBoolean = computed(() => props.lazyOnce ?? props.lazy)
```suggestion
const computedLazy = computed(() => props.lazyOnce ?? props.lazy)
```

Actual computed logic values like this can stay. But their variable name should probably be different.

2024-02-22 16:51 UTC, VividLemon commented on packages/bootstrap-vue-next/src/composables/useAriaInvalid.ts
> +    const resolvedState = toRef(state)
```suggestion
    const resolvedState = toValue(state)
```

Here you've done something, but I think you did it slightly be accident. You're creating a ref inside of a computed value. This is not very performant. Instead, you should use toValue here

(The previous code had these values declared outside. This is because we didn't want to init the useBooleanish composable inside computed. toRef is the same here, as we don't want to initialize refs in computeds. But we can use toValue here as its slightly more performant)

2024-02-22 16:51 UTC, VividLemon commented on packages/bootstrap-vue-next/src/composables/useFormCheck.ts
> +    )
Unlike the previous comment, in this one we do use a composable, and that composable depends on the reactive state of a toRef. So this code actually is best the way it was before

2024-02-22 16:51 UTC, VividLemon commented on packages/bootstrap-vue-next/src/types/BreakpointProps.ts
> +  xxl?: LiteralUnion<boolean, Numberish>
```suggestion
  sm?: boolean | Numberish
  md?: boolean | Numberish
  lg?: boolean | Numberish
  xl?: boolean | Numberish
  xxl?: boolean | Numberish
```

Literal union here has no effect

2024-02-22 16:51 UTC, VividLemon commented on packages/bootstrap-vue-next/src/types/RadiusElement.ts
> +  roundedEnd?: RadiusElement | boolean
```suggestion
  rounded?: boolean | RadiusElement
  roundedTop?: boolean | RadiusElement
  roundedBottom?: boolean | RadiusElement
  roundedStart?: boolean | RadiusElement
  roundedEnd?: boolean | RadiusElement
```

2024-02-22 16:51 UTC, VividLemon commented on packages/bootstrap-vue-next/src/types/TableTypes.ts
>    readonly perPage: number
```suggestion
export type BTableProviderContext = Readonly<{
  filter: string | undefined
  sortBy: string | undefined
  currentPage: number
  perPage: number
```

2024-02-22 16:51 UTC, VividLemon commented on packages/bootstrap-vue-next/src/types/TableTypes.ts
>  }
```suggestion
  sortDesc: boolean
}>
```

2024-02-22 16:52 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BAccordion/BAccordion.vue
> +const freeBoolean = computed(() => props.free)
```suggestion
```

2024-02-22 16:53 UTC, VividLemon commented on packages/bootstrap-vue-next/src/types/TableTypes.ts
>    readonly perPage: number
(Maybe)

2024-02-23 10:52 UTC, sceee commented on packages/bootstrap-vue-next/src/components/BTabs/BTab.vue
> +const lazyBoolean = computed(() => props.lazyOnce ?? props.lazy)
Generally, I agree.
But in this case, `computedLazy` clashes with an existing `computedLazy` (that does something different): https://github.com/bootstrap-vue-next/bootstrap-vue-next/pull/1791/files#diff-91a4211a7fd67ca96a56c6a3a098e92d7568ffad1258105546779bc809b90ff7R114

Do you have another preferred name?

2024-02-23 14:33 UTC, sceee commented
@VividLemon thank you for your thorough review.
Apart from the remaining comment (waiting for your feedback), I think I applied all your requested changes. Let me know if you would prefer other adjustments.

2024-02-23 15:04 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BFormGroup/BFormGroup.vue
> +    const floatingBoolean = computed(() => props.floating)
```suggestion
```

2024-02-23 15:04 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BFormInput/BFormInput.vue
> +const stateClass = useStateClass(props.state)
```suggestion
const stateClass = useStateClass(() => props.state)
```

2024-02-23 15:19 UTC, VividLemon requested changes

2024-02-23 15:20 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BFormSpinbutton/BFormSpinbutton.vue
> +        props.state === false || (!modelValue !== null && props.required) ? true : undefined
But idk

2024-02-27 08:14 UTC, sceee commented on packages/bootstrap-vue-next/src/components/BFormGroup/BFormGroup.vue
> +    const floatingBoolean = computed(() => props.floating)
Argh, I missed these, thanks.

2024-02-27 09:42 UTC, sceee commented on packages/bootstrap-vue-next/src/components/BFormSpinbutton/BFormSpinbutton.vue
> +        props.state === false || (!modelValue !== null && props.required) ? true : undefined
Hmm, in other components, something like this is used:
```
<output
    :aria-invalid="computedAriaInvalid">
    ...
</output>
...
const {computedAriaInvalid} = useFormInput(props, emit)
```

But I am actually not sure if this would also fit here as also in the docs for `Form Spinbutton` under `Required prop`, it also states this:
`Note that if the prop required is set, and the v-model is null, the attribute aria-invalid="true" will be rendered on the component`.

2024-02-27 09:53 UTC, sceee commented on packages/bootstrap-vue-next/src/components/BTable/BTable.vue
> +const busyBoolean = computed(() => busyModel.value)
This change now created an eslint warning
"Possible race condition: `busyModel.value` might be assigned based on an outdated state of `busyModel`."
in this line:
https://github.com/bootstrap-vue-next/bootstrap-vue-next/pull/1791/files#diff-729cc64555a2f321869087a61734032e55cf4b069c294260220584d53a143e26R593 ( https://github.com/sceee/bootstrap-vue-next/blob/7c1a6d54e0ef7e21499ba80bb9b335f6872f596c/packages/bootstrap-vue-next/src/components/BTable/BTable.vue#L593 )

I think that's because the `busyModel.value` in this `if` ( https://github.com/bootstrap-vue-next/bootstrap-vue-next/pull/1791/files#diff-729cc64555a2f321869087a61734032e55cf4b069c294260220584d53a143e26R578 ) might change in between before it is set to `false` in the finally because there is async code in between.

How would you resolve this?

2024-02-27 17:17 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BTable/BTable.vue
> +const busyBoolean = computed(() => busyModel.value)
There is technically a race condition here. However, it is not unexpected. 

Consider the following:

```ts
v-model:busy="myRef"

const myRef = ref(false)

const doStuff = () => {
  doStuffWithProvider() // The users version of props.provider
  myRef.value = true // They set the value to true
  // Promise is resolved
  // Finally in promise is run
  // Implicitly myRef.value = false
```
However, nothing in this chain is unexpected behavior. We still set the busy flag back to false when the promise is done. If the developer sets it to a different value between the time the provider func was called, we don't care (that's their problem)

2024-02-27 17:21 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BFormSpinbutton/BFormSpinbutton.vue
> +        props.state === false || (!modelValue !== null && props.required) ? true : undefined
Weird. Just going to ignore it then

2024-02-28 07:40 UTC, sceee commented on packages/bootstrap-vue-next/src/components/BTable/BTable.vue
> +const busyBoolean = computed(() => busyModel.value)
I added the linter warning ignore with a comment..

2024-02-28 23:13 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BFormFile/BFormFile.vue
> +const stateClass = useStateClass(props.state)
```suggestion
const stateClass = useStateClass(() => props.state)
```

2024-02-28 23:18 UTC, VividLemon requested changes

2024-02-28 23:18 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BFormGroup/BFormGroup.vue
> +    const computedAriaInvalid = useAriaInvalid(() => props.ariaInvalid, props.state)
```suggestion
    const computedAriaInvalid = useAriaInvalid(() => props.ariaInvalid, () => props.state)
```

2024-02-28 23:18 UTC, VividLemon approved these changes

2024-02-28 23:20 UTC, merged