fix(Bootstrap): remove deprecated classes
bootstrap-vue-next/bootstrap-vue-next pull request #1815
Opened 2024-03-15 21:44 UTC by anrolmar

# Describe the PR

This PR remove all the deprecated classes mentioned on https://github.com/bootstrap-vue-next/bootstrap-vue-next/issues/1779#issuecomment-1999436419

## PR checklist

**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix :bug: - `fix(...)`
- [ ] Feature - `feat(...)`
- [ ] ARIA accessibility - `fix(...)`
- [x] Documentation update - `docs(...)`
- [ ] Other (please describe)

**The PR fulfills these requirements:**

- [x] Pull request title and all commits follow the [**Conventional Commits**](https://www.conventionalcommits.org/) convention or has an [**override**](https://github.com/googleapis/release-please#how-can-i-fix-release-notes) in this pull request body **This is very important, as the `CHANGELOG` is generated from these messages, and determines the next version type. Pull requests that do not follow conventional commits or do not have an override will be denied**

2024-03-15 22:18 UTC, VividLemon requested changes

2024-03-15 22:18 UTC, VividLemon commented on apps/docs/src/data/components/modal.data.ts
> +          prop: 'titleVisibilityHiddenOnly',
This is a break change. It would be beneficial if you would reply to this with a collection of all the breaking changes so we can put them out for 0.17

2024-03-16 14:30 UTC, anrolmar commented on apps/docs/src/data/components/modal.data.ts
> +          prop: 'titleVisibilityHiddenOnly',
I did a search for 'titleSrOnly' and only BModal component uses titleSrOnly at this moment. I did a PR with that change, and I prepared the rest of the components updating ComponentProps, too

2024-03-19 00:49 UTC, dwgray commented on apps/docs/src/docs/components/input-group.md
> -**Note** Bootstrap 5 dropped `.input-group-append` and `.input-group-prepend`. You can now just add buttons and `.input-group-text` as direct children of the input groups. The sub-components are adde
I think this change is incorrect.  From the [BS5 migration guide](input-group-append): **Breaking** Dropped `.input-group-append` and `.input-group-prepend`. You can now just add buttons and `.input-group-text` as direct children of the input groups and it looks like the changes you made in the code were to change `Dropped .input-group-append` and `.input-group-prepend` to `.input-group-text`.

2024-03-23 07:10 UTC, anrolmar commented on apps/docs/src/docs/components/input-group.md
> -**Note** Bootstrap 5 dropped `.input-group-append` and `.input-group-prepend`. You can now just add buttons and `.input-group-text` as direct children of the input groups. The sub-components are adde
You're right. It's only remove the classes. It's about to add an `.input-group-text`with buttons.

2024-03-23 07:29 UTC, anrolmar commented on apps/docs/src/docs/components/input-group.md
> -**Note** Bootstrap 5 dropped `.input-group-append` and `.input-group-prepend`. You can now just add buttons and `.input-group-text` as direct children of the input groups. The sub-components are adde
I don't think so. We're using the right classes as you can see in the `BInputGroup` component:
```
<template>
  <component :is="tag" :id="id" class="input-group" :class="computedClasses" role="group">
    <slot name="prepend">
      <span v-if="hasPrepend" class="input-group-text">
        <!-- eslint-disable-next-line vue/no-v-html -->
        <span v-if="!!prependHtml" v-html="prependHtml" />
        <span v-else>{{ prepend }}</span>
      </span>
    </slot>
    <slot />
    <slot name="append">
      <span v-if="hasAppend" class="input-group-text">
        <!-- eslint-disable-next-line vue/no-v-html -->
        <span v-if="!!appendHtml" v-html="appendHtml" />
        <span v-else>{{ append }}</span>
      </span>
    </slot>
  </component>
</template>
```

The issue here is to fix the styling removing the `.input-group-append`and `.input-group-prepend` classes inside `_input-group.scss` to not miss behavior

2024-04-02 14:57 UTC, VividLemon commented on apps/docs/src/docs/components/input-group.md
> -**Note** Bootstrap 5 dropped `.input-group-append` and `.input-group-prepend`. You can now just add buttons and `.input-group-text` as direct children of the input groups. The sub-components are adde
@dwgray Your link sends me to the incorrect location. Can you repost it so I can review this and see who's correct, so I can make my decision?

2024-04-02 15:29 UTC, dwgray commented on apps/docs/src/docs/components/input-group.md
> -**Note** Bootstrap 5 dropped `.input-group-append` and `.input-group-prepend`. You can now just add buttons and `.input-group-text` as direct children of the input groups. The sub-components are adde
Sorry - that was less helpful without the link:  https://getbootstrap.com/docs/5.0/migration/#forms. I agree that @anrolmar is doing the right thing in the code, I just think the comment is wrong.  Note that Github is only highlighting the delete - its' actually the replace right after it that has on the face of it incorrect text. I think there may be an argument to delete the comment altogether (which may be what @anrolmar is saying).

2024-04-02 15:29 UTC, dwgray commented on apps/docs/src/docs/components/input-group.md
> +**Note** Bootstrap 5 dropped `.input-group-text` and `.input-group-text`. You can now just add buttons and `.input-group-text` as direct children of the input groups. The sub-components are added for
This is the text that I believe is wrong on the face based on [this](https://getbootstrap.com/docs/5.0/migration/#forms)

2024-05-30 08:08 UTC, xvaara commented
@anrolmar @dwgray @VividLemon  is this pr still in need of changes?

2024-05-30 14:38 UTC, VividLemon commented on apps/docs/src/docs/components/input-group.md
> -**Note** Bootstrap 5 dropped `.input-group-append` and `.input-group-prepend`. You can now just add buttons and `.input-group-text` as direct children of the input groups. The sub-components are adde
@xvaara It seems like if this has been dropped, that we could remove the sub-components -- I noticed this the other day, that the two components were exactly the same

2024-05-30 19:30 UTC, VividLemon commented on apps/docs/src/docs/components/input-group.md
> -**Note** Bootstrap 5 dropped `.input-group-append` and `.input-group-prepend`. You can now just add buttons and `.input-group-text` as direct children of the input groups. The sub-components are adde
I removed these two components in my feature branch

2024-10-13 00:35 UTC, xvaara commented
I'll create a new pr based on this.

2024-10-13 00:35 UTC, closed without merging