fix(BFormCheckbox): Fixes #1822 - Prevent empty string being cast to true
bootstrap-vue-next/bootstrap-vue-next pull request #1831
Opened 2024-03-27 17:25 UTC by dwgray

# Describe the PR

Fix #1822 (Empty string as entry in options array of BFormCheckboxGroup returned as true in v-model) by inlining the `string | boolean` part of the `CheckboxValue` type in the `defineProps` of `BFormCheckboxGroup.vue`.

According the the [vue docs](https://github.com/vuejs/core/issues/4480#issuecomment-910753900), the way to disable the boolean casting rule in this case is to make sure `string` comes before `boolean` in the type union.  Changing the type definition in `CheckBoxTypes.ts` wasn't sufficient because the [compiler-sfc doesn't crawl external files](https://github.com/vuejs/core/issues/4480#issuecomment-910753900), so prepended the `string | boolean` part of the union inline in the place that compiler-sfc uses.  This is somewhat ugly, but I believe it is better than the alternatives that I considered:
- Redefine `CheckboxValue` in `BFormCheckboxGroup.vue`
- Move the definitions in `CheckboxTypes.ts` to `BFormCheckboxGroup.vue` and then make `index.ts` in types refer to those definitions

## Small replication

See #1822 

## PR checklist

**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix :bug: - `fix(...)`
- [ ] Feature - `feat(...)`
- [ ] ARIA accessibility - `fix(...)`
- [ ] Documentation update - `docs(...)`
- [ ] Other (please describe)

**The PR fulfills these requirements:**

- [x] Pull request title and all commits follow the [**Conventional Commits**](https://www.conventionalcommits.org/) convention or has an [**override**](https://github.com/googleapis/release-please#how-can-i-fix-release-notes) in this pull request body **This is very important, as the `CHANGELOG` is generated from these messages, and determines the next version type. Pull requests that do not follow conventional commits or do not have an override will be denied**

2024-03-27 17:26 UTC, dwgray commented on packages/bootstrap-vue-next/src/types/CheckboxTypes.ts
> -  | boolean
This change isn't strictly necessary since the compiler-sfc never uses it, and AFAIK typescript itself doesn't care about the order.  But it seems like we should keep things consistent.

2024-04-02 14:45 UTC, VividLemon requested changes

2024-04-02 14:45 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BFormCheckbox/BFormCheckbox.vue
> +    value?: string | boolean | CheckboxValue
This change shouldn't be necessary.

2024-04-02 14:45 UTC, VividLemon commented on packages/bootstrap-vue-next/src/types/CheckboxTypes.ts
> -  | boolean
But this change should be.

Moving boolean after string is likely to fix the core issue. In relation to https://vuejs.org/guide/components/props.html#boolean-casting , the compiler should be able to crawl this file and apply string casting rules over boolean, with this change.

But I could be wrong, you should test to see if only this change works

2024-04-02 15:17 UTC, dwgray commented on packages/bootstrap-vue-next/src/types/CheckboxTypes.ts
> -  | boolean
I tried just changing the type declaration in here first.  That had no effect.  I quoted a reference from Evan You in the description of this PR, but looking at [the vue docs](https://vuejs.org/api/sfc-script-setup) is even clearer:

> In dev mode, the compiler will try to infer corresponding runtime validation from the types. For example here `foo: String` is inferred from the `foo: string` type. If the type is a reference to an imported type, the inferred result will be `foo: null` (equal to `any` type) since the compiler does not have information of external files.

2024-04-14 20:20 UTC, VividLemon commented
@dwgray merge conflict detected :robot:

2024-04-14 20:32 UTC, VividLemon approved these changes
Get your PR fixed :rofl:

2024-04-14 20:32 UTC, merged