feat(utils): inject getId to allow for custom id generation
bootstrap-vue-next/bootstrap-vue-next pull request #1836
Opened 2024-04-03 15:11 UTC by reubns

# Describe the PR
> [!WARNING]  
> Once Vue 3.5 is released, this PR will (likely) become obsolete in favour of the official method for generating IDs. If it is acceptable to wait for the 3.5 release, please close this PR.

Closes: #1730

This PR allows users to provide their own implementation for generating IDs. For example in Nuxt >= 3.10, to use SSR-friendly IDs.

```ts
// app.vue
provideGetId(() => useId())
```

> [!NOTE]  
> The Nuxt implementation above doesn't work for components with `inheritAttrs: false` due to the implementation of Nuxt's `useId`. For example, `BFormRadio`.

Credits: https://github.com/tailwindlabs/headlessui/pull/2959 https://github.com/radix-vue/radix-vue/pull/718

## Small replication

Issue is described in #1730

## PR checklist

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix :bug: - `fix(...)`
- [x] Feature - `feat(...)`
- [ ] ARIA accessibility - `fix(...)`
- [ ] Documentation update - `docs(...)`
- [ ] Other (please describe)

**The PR fulfills these requirements:**

- [x] Pull request title and all commits follow the [**Conventional Commits**](https://www.conventionalcommits.org/) convention or has an [**override**](https://github.com/googleapis/release-please#how-can-i-fix-release-notes) in this pull request body **This is very important, as the `CHANGELOG` is generated from these messages, and determines the next version type. Pull requests that do not follow conventional commits or do not have an override will be denied**

2024-04-03 21:31 UTC, VividLemon requested changes

2024-04-03 21:31 UTC, VividLemon commented on packages/bootstrap-vue-next/src/utils/getId.ts
> +import {inject, type InjectionKey, provide} from 'vue'
This file should now be located in the composables directory, since it's no longer a purely functional util

2024-04-03 21:31 UTC, VividLemon commented on packages/bootstrap-vue-next/src/utils/getId.ts
> +import {inject, type InjectionKey, provide} from 'vue'
Likely it's best in /useId

2024-04-03 21:31 UTC, VividLemon commented on packages/bootstrap-vue-next/src/utils/getId.ts
> +export const provideGetId = (fn: () => string) => provide(GET_ID, fn)
It may be better to register this as a global plugin. Similar to toastPlugin, etc. 

Then we install it automatically in the createBootstrap function

Then in Nuxt, when we consume createBootstrap(), we pass in the Nuxt useId function, so that way we automatically register this in Vue, and automatically register it in Nuxt for stable ids.

2024-04-03 21:31 UTC, VividLemon commented on packages/bootstrap-vue-next/src/utils/getId.ts
> +export const provideGetId = (fn: () => string) => provide(GET_ID, fn)
(I'm not sure how provide/inject with a runtime plugin that purpose is to generate stable ids will work. Some spot checking to make sure the ids become stable on the Nuxt playground will be useful)

2024-04-04 14:06 UTC, reubns commented on packages/bootstrap-vue-next/src/utils/getId.ts
> +export const provideGetId = (fn: () => string) => provide(GET_ID, fn)
@VividLemon Thank you for the detailed review.

I've created `idPlugin` to allow this to be automatically registered in Vue and Nuxt.

Regarding the playground. Initially, changing to the plugin caused more hydration errors 🥲. Adding `.replace(':', '_'),` to the function provided to Nuxt `createBootstrap` means that the playground raises no errors. Although, this feels like a workaround https://github.com/nuxt/nuxt/pull/26315#issuecomment-2002563619 to accommodate the Nuxt implementation of `useId`.

I thought this a good point to check your thoughts on the current implementation.

2024-04-04 15:54 UTC, xvaara commented
Tested with nuxt kitchensink (all the playground components) and most of the hydration mismatches are gone :)

2024-04-04 18:21 UTC, VividLemon requested changes

2024-04-04 18:21 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BFormGroup/BFormGroup.vue
> +    const labelId = labelContent ? useId(undefined, '_BV_label_').value : null
This stuff should go into the setup area...  I dont know if composables can go into the render func area. I would guess this id would rebuild on every render

2024-04-04 18:21 UTC, VividLemon commented on packages/nuxt/src/runtime/createBootstrap.ts
> +          getId: () => useId().replace(':', '_'),
Dont really see the point of the replace

2024-04-05 14:08 UTC, reubns commented on packages/bootstrap-vue-next/src/components/BFormGroup/BFormGroup.vue
> +    const labelId = labelContent ? useId(undefined, '_BV_label_').value : null
@VividLemon Would you prefer a separate PR for this? I can reproduce the id rebuild when rendering but believe the same behaviour existed before this PR.

2024-04-14 00:10 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BFormGroup/BFormGroup.vue
> +    const labelId = labelContent ? useId(undefined, '_BV_label_').value : null
Yes

2024-04-14 00:10 UTC, VividLemon approved these changes

2024-04-14 20:22 UTC, merged