docs(BCheckBox*): Small changes to get documentation to parity
bootstrap-vue-next/bootstrap-vue-next pull request #1873
Opened 2024-04-30 20:16 UTC by dwgray

# Describe the PR

This PR should get the documents up to date and confirm that they are [at parity](https://1drv.ms/x/s!AiUqzkjNYGL6ieBPpQpcR41wo1laZQ?e=DYykFl) with BSV and BS5

- Document 'Without Labels'
- Document all types
- Export `AriaInvalid`, which was used but not exported
- Start general migration docs to cover cases that are used in these components

## Small replication

A small replication or video walkthrough can help demonstrate the changes made. This is optional, but can help observe the intended changes. A mentioned issue that contains a replication also works.

## PR checklist

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix :bug: - `fix(...)`
- [ ] Feature - `feat(...)`
- [ ] ARIA accessibility - `fix(...)`
- [X] Documentation update - `docs(...)`
- [ ] Other (please describe)

**The PR fulfills these requirements:**

- [X] Pull request title and all commits follow the [**Conventional Commits**](https://www.conventionalcommits.org/) convention or has an [**override**](https://github.com/googleapis/release-please#how-can-i-fix-release-notes) in this pull request body **This is very important, as the `CHANGELOG` is generated from these messages, and determines the next version type. Pull requests that do not follow conventional commits or do not have an override will be denied**

2024-04-30 20:20 UTC, dwgray commented on apps/docs/src/docs/migration-guide.md
>  <MigrationWrapper v-for="(item, i) in changes" :key="i" v-bind="item" />
@VividLemon I didn't follow your pattern with the migration wrapper here. The problem is that vue components are rendered after the markdown is all transformed, so using this technique I don't see any way to get markdown sections (and other markdown, like the examples) into this document.

Let me know if you can think of a way to get the best of both worlds.  The only way I could see to do that is to write a markdown-it plugin, which seems like a pretty heavy lift for this, but maybe I'm missing something simple.

2024-04-30 22:23 UTC, VividLemon requested changes

2024-04-30 22:23 UTC, VividLemon commented on apps/docs/src/docs/components/form-checkbox.md
> +In order to ommit labels as described in the
```suggestion
In order to omit labels as described in the
```

2024-04-30 22:23 UTC, VividLemon commented on apps/docs/src/docs/migration-guide.md
> +    <b-form-checkbox v-model="checked" :indeterminate.sync="indeterminate">
Pascal case for consistency

2024-05-01 04:49 UTC, dwgray commented on apps/docs/src/docs/migration-guide.md
> +    <b-form-checkbox v-model="checked" :indeterminate.sync="indeterminate">
Got it. I went back and forth on this, landing on kebab-case, since that's what the BSV sample that I pulled had.  But now that I see this, I agree that it makes the relevant change stand out more.

2024-05-08 21:37 UTC, merged