fix(BFormFloatingLabel): Clean up props
bootstrap-vue-next/bootstrap-vue-next pull request #1991
Opened 2024-07-01 23:55 UTC by dwgray

# Describe the PR

Remove two props related to floating labels that don't work.

1. The `floating` prop on `BForm` does nothing other than add `form-floating` class to the form element. According to the [BS5 docs](https://getbootstrap.com/docs/5.3/forms/floating-labels/), that's not how this class works. You need to wrap pairs of control/label in a containing element that has the class applied, which is what `BFormFloatingLabel` does.
2. The `text` prop on `BFormFloatingLabel` used the value of that property as the fallback content of the `default` slot. This doesn't work, that slot has to contain one of select few form controls. Putting plain text there just generates ugliness.

## Small replication

[stackblitz](https://stackblitz.com/edit/github-llmgfm?file=src%2Fcomponents%2FComp.vue)

```
<template>
  <Container>
    <BRow
      ><BCol>
        <BForm class="floating-label">
          <BInput
            id="floatingEmail"
            type="email"
            class="form-control"
            placeholder="Email address"
            label="Email address"
          />
          <BInput
            id="floatingPassword"
            type="password"
            placeholder="Password"
            label="Password"
          />
        </BForm> </BCol
    ></BRow>
    <BRow
      ><BCol>
        <BForm>
          <BFormFloatingLabel
            label="Email address"
            label-for="floatingEmail"
            class="my-2"
            text="Testing floating label text"
          >
          </BFormFloatingLabel>
        </BForm> </BCol
    ></BRow>
  </Container>
</template>
```
## PR checklist

**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix :bug: - `fix(...)`
- [ ] Feature - `feat(...)`
- [ ] ARIA accessibility - `fix(...)`
- [ ] Documentation update - `docs(...)`
- [ ] Other (please describe)

**The PR fulfills these requirements:**

- [x] Pull request title and all commits follow the [**Conventional Commits**](https://www.conventionalcommits.org/) convention or has an [**override**](https://github.com/googleapis/release-please#how-can-i-fix-release-notes) in this pull request body **This is very important, as the `CHANGELOG` is generated from these messages, and determines the next version type. Pull requests that do not follow conventional commits or do not have an override will be denied**

2024-07-01 23:56 UTC, dwgray commented on packages/bootstrap-vue-next/src/components/BForm/BForm.vue
> -  floating: false,
I have notes in the PR description and an example as to why I believe this property should be removed.

2024-07-01 23:57 UTC, dwgray commented on packages/bootstrap-vue-next/src/components/BForm/BFormFloatingLabel.vue
> -  default?: (props: Record<string, never>) => any
I have notes in the PR description and an example as to why I believe this property should be removed.

2024-07-02 00:02 UTC, VividLemon commented
Not sure why you think you can't have form-floating on a form element
![image](https://github.com/bootstrap-vue-next/bootstrap-vue-next/assets/31498096/56fd4a18-08a6-46ce-86f5-6f4a3252464e)

Idrk why one would want to use form over a div in this case though

2024-07-02 00:16 UTC, dwgray commented
I think those examples in BS5 are misleading. They only work if you have a single control/label combination in the form.  See [this stackblitz](https://stackblitz.com/edit/aqveji?file=index.html) for a counter-example in native BS5.

Us putting a prop called `floating` implies to me that all of the controls in the form will somehow be floating (maybe we could implement that, but it would be complicated and is not accomplished by merely putting `form-floating` on the form element. Someone who wanted to mimic the single control example could add the class on the `BForm` themselves and would hopefully know enough not to shoot themselves in the foot.

If you really want to keep that prop in, let me know.  In that case, I'd also like to add some stuff to the docs so people don't assume it does more than it does. Alternately, I could take it out and include a single form control example. Let me know which you prefer.

2024-07-06 23:53 UTC, VividLemon commented
Regardless on if the class is misleading, it is native bootstrap form code. There's no reason to remove it

2024-07-06 23:57 UTC, VividLemon requested changes

2024-07-06 23:57 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BForm/BForm.vue
> -  'form-floating': props.floating,
This is probably my only issue with this PR. I suppose some components could benefit from making their slots not optional as shwon in BFormFloatingLabel. But this could be something else, or not added

2024-07-08 18:42 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BForm/form.spec.ts
```suggestion

it('has class form-floating when prop floating', async () => {
    const wrapper = mount(BForm, {
      props: {floating: true},
    })
    expect(wrapper.classes()).toContain('form-floating')
    await wrapper.setProps({floating: false})
    expect(wrapper.classes()).not.toContain('form-floating')
  })

```

2024-07-08 18:42 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BForm/form.spec.ts
> +it('has class form-floating when prop floating', async () => {
```suggestion
  it('has class form-floating when prop floating', async () => {
```

2024-07-08 18:45 UTC, VividLemon approved these changes

2024-07-08 18:45 UTC, merged

2024-07-08 18:47 UTC, dwgray commented
> Regardless on if the class is misleading, it is native bootstrap form code. There's no reason to remove it

Okay, I will defer to you on this. Added that property back in. I have #2003 that was in progress when I saw this that fixes some other docs issues. I've added some documentation about the `floating` label that I hope will make its limited value clear to users.