feat(BFormDatalist): Initial implementation
bootstrap-vue-next/bootstrap-vue-next pull request #2036
Opened 2024-07-13 18:49 UTC by dwgray

# Describe the PR

A clear and concise description of what the pull request does.

## Small replication

A small replication or video walkthrough can help demonstrate the changes made. This is optional, but can help observe the intended changes. A mentioned issue that contains a replication also works.

## PR checklist

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix :bug: - `fix(...)`
- [ ] Feature - `feat(...)`
- [ ] ARIA accessibility - `fix(...)`
- [ ] Documentation update - `docs(...)`
- [ ] Other (please describe)

**The PR fulfills these requirements:**

- [ ] Pull request title and all commits follow the [**Conventional Commits**](https://www.conventionalcommits.org/) convention or has an [**override**](https://github.com/googleapis/release-please#how-can-i-fix-release-notes) in this pull request body **This is very important, as the `CHANGELOG` is generated from these messages, and determines the next version type. Pull requests that do not follow conventional commits or do not have an override will be denied**

2024-07-13 18:51 UTC, dwgray commented on packages/bootstrap-vue-next/src/composables/useFormSelect.ts
> +    const opts: undefined | (unknown | Record<string, unknown>)[] = get(
I'm using this composable in Datalists, which don't support options groups, so they don't have the optionsField property.  There are probably other ways to get around this, but it seems like this is a more robust way to handle the default case for other uses of this composable anyway, unless I'm missing something?

2024-07-13 18:52 UTC, dwgray commented on packages/bootstrap-vue-next/src/composables/useFormSelect.ts
> +        label: get(option, (props.labelField as string) ?? 'label') || text,
same comment as with optionsField

2024-07-13 18:53 UTC, dwgray commented on packages/bootstrap-vue-next/src/components/BForm/BFormDatalist.vue
> +    console.warn('Datalist may not contain complex options', computedId.value)
I'd like to use the same mechansisms we have in place for options lists, but datafields don't allow for options groups. I'm not seeing a consistent way to manage runtime errors for a case like this, happy with any guidance for managing this differently.

2024-07-13 18:57 UTC, dwgray commented
@VividLemon This is the first component I've written from scratch, so I'd appreciate any early feedback you have on this before I document it and write tests (also interested in what you'd test on this - this is basically a very paired-down version of `BFormSelect` and that doesn't have direct testing - most of the complex code is shared code that is under test).

BTW - I'm not planning on filling in significant sized holes as I'm going through the parity/documentation pass - I think it's more important that I get through a first round. However, this helper component is actually something that I use and is blocking my next round of page conversions - it just happened to be related to stuff that I'm touching with the parity work.

2024-07-16 19:25 UTC, dwgray commented
> @VividLemon This is the first component I've written from scratch...

This is ready to go as far as I'm concerned. But as I noted, this is my first component from scratch...

2024-07-21 15:45 UTC, VividLemon requested changes

2024-07-21 15:45 UTC, VividLemon commented on packages/bootstrap-vue-next/src/composables/useFormSelect.ts
> +    const opts: undefined | (unknown | Record<string, unknown>)[] = get(
`(unknown | Record<string, unknown>)[] = get(`
This is bad code on my part, as type 'unknown' already is inclusive of `Record<string, unknown>`

2024-07-21 15:45 UTC, VividLemon commented on packages/bootstrap-vue-next/src/composables/useFormSelect.ts
> +    const opts: undefined | (unknown | Record<string, unknown>)[] = get(
Seemingly the best option would be to pass it in the parent component. 

`useFormSelect(() => props.options, computed(() => (...props, optionsField: props.optionsField ?? 'options'}))`

etc etc

2024-07-21 15:45 UTC, VividLemon commented on packages/bootstrap-vue-next/src/composables/useFormSelect.ts
> +    const opts: undefined | (unknown | Record<string, unknown>)[] = get(
With this change this file would be pretty unchanged

2024-07-21 15:45 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BForm/BFormDatalist.vue
> +const props = useDefaults(_props, 'BFormSelect')
This seems like it needs a different key `BFormSelect`

2024-07-21 15:45 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BForm/BFormDatalist.vue
> +    console.warn('Datalist may not contain complex options', computedId.value)
You'd have to show some code for what you tried.

I don't like this code here. 

I think if this component never has a situation where isComplex should be true, then it should never be an issue and this code should be removed. Ie if it does ever happen somehow, we should simply ignore it as its user error

Hypothetically this is something that would be validated by TS. Don't know how strongly typed that is though

2024-07-21 21:38 UTC, dwgray commented on packages/bootstrap-vue-next/src/components/BForm/BFormDatalist.vue
> +    console.warn('Datalist may not contain complex options', computedId.value)
Here's a fiddle https://jsfiddle.net/ohdwg/6tzu4nqc/2/ showing that options groups aren't supported in data lists.  They're also not documented on Mozilla for datalist: https://jsfiddle.net/ohdwg/6tzu4nqc/2/ while they are for  select: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select

I agree that typing the property would be the preferred way to go. But, the types have to be loose enough to allow substituting key names for the different fields (diabledField, htmlField, textField, valueField, labelField, optionsField).

I reworked this to silently ignore complex options and addressed the limitation in the documentation. I considered flattening the list (which is closer to what the native control does if you add in complex options), but then I'd have to add back in `labelField` and `optionsField` which seems like ugly complexity for something that is getting flattened back out. Short of pulling off some typescript voodoo, that's the best I can come up with.

2024-07-21 21:39 UTC, dwgray commented on packages/bootstrap-vue-next/src/composables/useFormSelect.ts
> +    const opts: undefined | (unknown | Record<string, unknown>)[] = get(
Thanks - I like that better.

2024-07-21 21:39 UTC, dwgray commented on packages/bootstrap-vue-next/src/components/BForm/BFormDatalist.vue
> +const props = useDefaults(_props, 'BFormSelect')
Fixed.

2024-07-21 21:41 UTC, dwgray commented on packages/bootstrap-vue-next/src/composables/useFormSelect.ts
> +    const opts: undefined | (unknown | Record<string, unknown>)[] = get(
Sorry - yeah, I can change it to just unknown if you like. I can also take one more run at trying to more strictly type this - but I'd like you take on whether you think it's even doable before I spend more time on it (with the issue of the field names being fungible at runtime that I noted below).

2024-07-22 19:32 UTC, dwgray commented on packages/bootstrap-vue-next/src/composables/useFormSelect.ts
> +    const opts: undefined | (unknown | Record<string, unknown>)[] = get(
On closer examination, I believe `undefined | unknown[]` is a slight improvement to this declaration. I think that's the best we can do in that case.

2024-07-22 23:33 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BForm/BFormDatalist.vue
> +const props = useDefaults(_props, 'BFormSelect')
No, I mean it's currently BFormSelect, but seems to need `BFormDatalist`

2024-07-22 23:44 UTC, dwgray commented on packages/bootstrap-vue-next/src/components/BForm/BFormDatalist.vue
> +const props = useDefaults(_props, 'BFormSelect')
Sorry - something I don't understand is going on with github's view of this. If you look at [this commit](https://github.com/bootstrap-vue-next/bootstrap-vue-next/pull/2036/commits/9145882f360bfaed693326c4098f22221930668a) - I've changed line #33 of BFormDatlist.vue to 
`const props = useDefaults(_props, 'BFormDatalist')`, which is what you want, right? This comment is marked as outdated, so it's not updating the diff here? Not sure why.

2024-08-06 14:46 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BForm/BFormDatalist.vue
> +  computed(() => ({...props, optionsField: 'options', labelField: 'label'})).value
This is wrong. You should be passing in a Ref, not its .value =>

ie. if props changes, useFormSelect wont update

```suggestion
  computed(() => ({...props, optionsField: 'options', labelField: 'label'}))
```

2024-08-06 14:47 UTC, VividLemon approved these changes

2024-08-06 14:54 UTC, VividLemon requested changes

2024-08-06 14:54 UTC, VividLemon commented on packages/bootstrap-vue-next/src/composables/useFormSelect.ts
> +    const opts: undefined | unknown[] = props.optionsField
Some of the code for useFormSelect needs to be rewritten to support reactive inputs

This function
![image](https://github.com/user-attachments/assets/678ca384-6d56-441a-84b2-2515f2698c1e)
shadows this parameter
![image](https://github.com/user-attachments/assets/1100dbd9-6663-4953-87f1-def100102817)
(Two duplicate variable names)

```ts
export default (options: MaybeRefOrGetter, props: Record<string, unknown>) => {
```
Options needs a generic input `MaybeRefOrGetter<unknown>` would suffice, unless there's some more strict input we can use

props should be `props: MaybeRefOrGetter<Record<string, unknown>>` which will likely need to be satisfied with

```ts
 const propsValue = readonly(toRef(props))
```

or

```ts
  const normalizeOption = (
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    option: any
  ): ComplexSelectOptionRaw | SelectOption => {
    const propsValue = toValue(props) // <-- then use this in the function
    if (typeof option === 'string') {
```

I prefer the first though. Perhaps `normalizeOptions(toValue(options)))` should be

```ts
const optionsValue = readonly(toRef(options))
const normalizedOptions = computed(() => normalizeOptions(optionsValue.value))
```
Here as well though

2024-08-06 20:24 UTC, VividLemon requested changes

2024-08-06 20:24 UTC, VividLemon commented on packages/bootstrap-vue-next/src/composables/useFormSelect.ts
> +
```suggestion
export default (
  options: MaybeRefOrGetter<Readonly<unknown[]>>,
  props: MaybeRefOrGetter<Record<string, unknown>>
) => {
  const propsValue = readonly(toRef(props)) // as Readonly<Record<string, unknown>>
  const optionsValue = readonly(toRef(options))

  const isComplex = (option: unknown): option is ComplexSelectOptionRaw =>
    typeof option === 'object' && option !== null && 'label' in option

  const normalizeOption = (
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    option: any
  ): ComplexSelectOptionRaw | SelectOption => {
```

2024-08-06 20:24 UTC, VividLemon commented on packages/bootstrap-vue-next/src/composables/useFormSelect.ts
> +  const optionsValue = readonly(toRef(options))
```suggestion
```

2024-08-06 20:25 UTC, VividLemon commented on packages/bootstrap-vue-next/src/composables/useFormSelect.ts
> +  options: MaybeRefOrGetter<Readonly<unknown[]>>,
```suggestion
  options: MaybeRefOrGetter<unknown[]>,
```

2024-08-06 20:26 UTC, VividLemon commented on packages/bootstrap-vue-next/src/composables/useFormSelect.ts
> +  options: MaybeRefOrGetter<Readonly<unknown[]>>,
```suggestion
  options: MaybeRefOrGetter<ReadonlyArray<unknown>>,
```

2024-08-06 20:27 UTC, VividLemon commented on packages/bootstrap-vue-next/src/composables/useFormSelect.ts
> +    opts: Readonly<unknown[]>
```suggestion
    opts: ReadonlyArray<unknown>
```

2024-08-06 20:27 UTC, VividLemon approved these changes

2024-08-06 20:36 UTC, merged