change renderorskip to wrapper, add our own teleport logic.
bootstrap-vue-next/bootstrap-vue-next pull request #2162
Opened 2024-08-30 12:35 UTC by xvaara

# Describe the PR

This fixes the teleport problems are having. It seems upstream isn't interested in fixing this any time soon.
Renamed render or skip to BWrapper. 

## Small replication

A small replication or video walkthrough can help demonstrate the changes made. This is optional, but can help observe the intended changes. A mentioned issue that contains a replication also works.

## PR checklist

**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix :bug: - `fix(...)`
- [ ] Feature - `feat(...)`
- [ ] ARIA accessibility - `fix(...)`
- [ ] Documentation update - `docs(...)`
- [ ] Other (please describe)

**The PR fulfills these requirements:**

- [x] Pull request title and all commits follow the [**Conventional Commits**](https://www.conventionalcommits.org/) convention or has an [**override**](https://github.com/googleapis/release-please#how-can-i-fix-release-notes) in this pull request body **This is very important, as the `CHANGELOG` is generated from these messages, and determines the next version type. Pull requests that do not follow conventional commits or do not have an override will be denied**

2024-09-05 14:02 UTC, VividLemon requested changes

2024-09-05 14:02 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BTeleport.vue
> +  name: 'BTeleport',
It would be beneficial to rebase this to my branch https://github.com/bootstrap-vue-next/bootstrap-vue-next/pull/2147 . The structure of the directories have changed (read README).

Second, let's make these internal components have a name not prepended with `B` to also indicate that they are not exposed components

2024-09-05 14:02 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BTeleport.vue
> +  name: 'BTeleport',
When you've done that, feel free to merge request this PR into my PR. That would make things easier ig

2024-09-12 22:17 UTC, VividLemon requested changes

2024-09-12 22:17 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BDropdown/BDropdown.vue
> +../BWrapper.vue
```suggestion
```

2024-09-12 22:17 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BFormRadio/BFormRadio.vue
> +../BWrapper.vue
```suggestion
```

2024-09-12 22:17 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BTeleport.vue
Rename this file. It is not an exposed component so it doesn't make sense to have it prefixed with "B".

2024-09-12 22:17 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BWrapper.vue
Rename this file. It is not an exposed component so it doesn't make sense to have it prefixed with "B".

2024-09-13 07:57 UTC, xvaara commented on packages/bootstrap-vue-next/src/components/BDropdown/BDropdown.vue
> +../BWrapper.vue
Something adds these in :D

2024-09-14 14:43 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BOffcanvas/BOffcanvas.vue
> +../ConditionalTeleport.vue
```suggestion
```

2024-09-14 14:44 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BDropdown/BDropdown.vue
> +../ConditionalTeleport.vue
```suggestion
```

2024-09-14 14:44 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BModal/BModal.vue
> +../ConditionalTeleport.vue
```suggestion
```

2024-09-14 14:44 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BModal/BModalOrchestrator.vue
> +../ConditionalTeleport.vue
```suggestion
```

2024-09-14 14:44 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BPopover/BPopover.vue
> +../ConditionalTeleport.vue
```suggestion
```

2024-09-14 14:44 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BToast/BToastOrchestrator.vue
> +../ConditionalTeleport.vue
```suggestion
```

2024-09-14 14:45 UTC, VividLemon approved these changes

2024-09-14 14:47 UTC, merged