feat(BDropdown): add variant, classes and correct attrs to text sub components
bootstrap-vue-next/bootstrap-vue-next pull request #2258
Opened 2024-10-10 15:54 UTC by xvaara

# Describe the PR

closes #2244

## Small replication

A small replication or video walkthrough can help demonstrate the changes made. This is optional, but can help observe the intended changes. A mentioned issue that contains a replication also works.

## PR checklist

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix :bug: - `fix(...)`
- [x] Feature - `feat(...)`
- [ ] ARIA accessibility - `fix(...)`
- [ ] Documentation update - `docs(...)`
- [ ] Other (please describe)

**The PR fulfills these requirements:**

- [x] Pull request title and all commits follow the [**Conventional Commits**](https://www.conventionalcommits.org/) convention or has an [**override**](https://github.com/googleapis/release-please#how-can-i-fix-release-notes) in this pull request body **This is very important, as the `CHANGELOG` is generated from these messages, and determines the next version type. Pull requests that do not follow conventional commits or do not have an override will be denied**

2024-10-11 00:04 UTC, dwgray commented
In BSV, the `innerClass`, when implemented, was more specific - e.g. `formClass`, `textClass`, etc. I could argue either way for doing that vs. using the more generic term in all cases. I'm happy whichever way you want to go. But I do strongly prefer that we maintain internal consistency. If you want to make everything `innerClass`, that would require changing basically all the dropdown sub-components you didn't touch here from their specific names to `innerClass`, or to go the other direction use the same prop names as BSV used. @VividLemon , do you have any thoughts on this?

2024-10-11 00:57 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BDropdown/BDropdownDivider.vue
> +  innerClass: undefined,
Looks odd I agree

2024-10-11 08:15 UTC, xvaara commented on packages/bootstrap-vue-next/src/components/BDropdown/BDropdownDivider.vue
> +  innerClass: undefined,
ups, that was a mistake

2024-10-11 14:33 UTC, VividLemon requested changes

2024-10-11 14:33 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BDropdown/dropdown-text.spec.ts
> -  it('renders prop text', () => {
Why is this removed

2024-10-11 17:59 UTC, xvaara commented on packages/bootstrap-vue-next/src/components/BDropdown/dropdown-text.spec.ts
> -  it('renders prop text', () => {
At some point I removed the test prop.. I'll return the test

2024-10-12 18:37 UTC, dwgray commented
@xvaara I believe that we should implement `novalidate` and `validated` on `BDropdownForm` - these are implemented on `BForm` and `BNavForm`, so it would be weird not to have them on `BDropdownForm`.  I've got a commit with these changes https://github.com/bootstrap-vue-next/bootstrap-vue-next/commit/7b51923355ba4e0216e95b0f31d54dd1235e1a09 - I don't see a way to apply my commit to your PR, but if you can do it or point me at how to do it that would be great.

I'd like to mark `disabled` on `BDropdownForm` as deprecated - in BSV, this appears to disable all of the controls on the form. This is _not implemented_ on `BForm` or `BNavForm` in BSV. This is certainly something that could be added after a v1 in a non-breaking way if someone feels it's necessary.

2024-10-12 23:45 UTC, xvaara commented
@dwgray I added the stuff from that commit to this.

2024-10-13 00:00 UTC, dwgray approved these changes
LGTM with the exception of the duplicate test.

2024-10-13 00:18 UTC, merged