BTable : make it possible to style cutom footers
bootstrap-vue-next/bootstrap-vue-next pull request #2314
Opened 2024-10-29 11:25 UTC by tbl0605

Hi,
I recently tried to migrate a BTable that has a custom footer.
Sadly it's not possible to add a variant (or some styles) on the BTfoot component itself.
In following example, the `dark` variant would not be applied on the footer:

```vue
    <BTable foot-variant="dark" ... >
      <template v-slot:custom-foot="fields">
        <BTr>
          <BTh class="text-center align-middle text-nowrap">{{ value1 }}</BTh>
          <BTh class="text-center align-middle text-nowrap">{{ value2 }}</BTh>
        </BTr>
      </template>
    </BTable>
```

This little patch should be enough to fix the issue.

## PR checklist

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix :bug: - `fix(...)`
- [X] Feature - `feat(...)`
- [ ] ARIA accessibility - `fix(...)`
- [ ] Documentation update - `docs(...)`
- [ ] Other (please describe)

**The PR fulfills these requirements:**

- [X] Pull request title and all commits follow the [**Conventional Commits**](https://www.conventionalcommits.org/) convention or has an [**override**](https://github.com/googleapis/release-please#how-can-i-fix-release-notes) in this pull request body **This is very important, as the `CHANGELOG` is generated from these messages, and determines the next version type. Pull requests that do not follow conventional commits or do not have an override will be denied**

2024-10-31 22:19 UTC, VividLemon requested changes

2024-10-31 22:19 UTC, VividLemon commented on packages/bootstrap-vue-next/src/components/BTable/BTableLite.vue
> +      :class="props.tfootClass"
```ts
const footerProps = computed(() => ({
  variant: props.footerVariant,
  class: props.tfootClass
})
```

Then

```suggestion
      v-bind="footerProps"
```

Apply this to both uses of the BTfoot component, which should make it more resilient to additions

2024-11-01 18:41 UTC, tbl0605 commented on packages/bootstrap-vue-next/src/components/BTable/BTableLite.vue
> +      :class="props.tfootClass"
Done!
Thank you for your review :)

2024-11-04 13:43 UTC, VividLemon approved these changes

2024-11-04 13:43 UTC, merged