docs: Enable optional type-checking and clean up several issues
bootstrap-vue-next/bootstrap-vue-next pull request #2419
Opened 2024-12-05 20:08 UTC by dwgray

# Describe the PR

See #2418 

This PR sets up a type-check command for docs and cleans up the errors in component reference data and samples.

I'll chip away at the other errors as time permits

## Small replication

N/A

## PR checklist

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix :bug: - `fix(...)`
- [ ] Feature - `feat(...)`
- [ ] ARIA accessibility - `fix(...)`
- [x] Documentation update - `docs(...)`
- [ ] Other (please describe)

**The PR fulfills these requirements:**

- [x] Pull request title and all commits follow the [**Conventional Commits**](https://www.conventionalcommits.org/) convention or has an [**override**](https://github.com/googleapis/release-please#how-can-i-fix-release-notes) in this pull request body **This is very important, as the `CHANGELOG` is generated from these messages, and determines the next version type. Pull requests that do not follow conventional commits or do not have an override will be denied**

2024-12-06 00:11 UTC, VividLemon requested changes

2024-12-06 00:11 UTC, VividLemon commented on apps/docs/package.json
>      "build": "cross-env NODE_OPTIONS=--max-old-space-size=4096 vitepress build",
Add build-only variant

2024-12-06 00:11 UTC, VividLemon commented on package.json
> +    "type-check": "turbo run type-check",
Add a build-only variant

2024-12-06 00:46 UTC, dwgray commented on apps/docs/package.json
>      "build": "cross-env NODE_OPTIONS=--max-old-space-size=4096 vitepress build",
I think I have this set up the way you're asking. We can now do `pnpm build-only` from the root and it will do builds without type-check. Once I have `type-check` running in `docs` without errors, `build` will become type-check && build-only.

2024-12-06 00:46 UTC, dwgray commented on package.json
> +    "type-check": "turbo run type-check",
See above.

2024-12-07 02:13 UTC, VividLemon approved these changes

2024-12-07 02:13 UTC, merged